// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

/**
 * Protobuf type {@code org.monitoring.proto.AGDeviceInfo}
 */
public  final class AGDeviceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.AGDeviceInfo)
    AGDeviceInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AGDeviceInfo.newBuilder() to construct.
  private AGDeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AGDeviceInfo() {
    equipName_ = "";
    equipId_ = "";
    gateIp_ = "";
    gateType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AGDeviceInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AGDeviceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            equipName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            equipId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            gateIp_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            gateType_ = s;
            break;
          }
          case 42: {
            org.network.monitorandcontrol.ag.GateInfo.Builder subBuilder = null;
            if (gateInfo_ != null) {
              subBuilder = gateInfo_.toBuilder();
            }
            gateInfo_ = input.readMessage(org.network.monitorandcontrol.ag.GateInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gateInfo_);
              gateInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGDeviceInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGDeviceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.ag.AGDeviceInfo.class, org.network.monitorandcontrol.ag.AGDeviceInfo.Builder.class);
  }

  public static final int EQUIP_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object equipName_;
  /**
   * <code>string equip_name = 1;</code>
   * @return The equipName.
   */
  public java.lang.String getEquipName() {
    java.lang.Object ref = equipName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      equipName_ = s;
      return s;
    }
  }
  /**
   * <code>string equip_name = 1;</code>
   * @return The bytes for equipName.
   */
  public com.google.protobuf.ByteString
      getEquipNameBytes() {
    java.lang.Object ref = equipName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      equipName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EQUIP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object equipId_;
  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  public java.lang.String getEquipId() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      equipId_ = s;
      return s;
    }
  }
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  public com.google.protobuf.ByteString
      getEquipIdBytes() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      equipId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GATE_IP_FIELD_NUMBER = 3;
  private volatile java.lang.Object gateIp_;
  /**
   * <code>string gate_ip = 3;</code>
   * @return The gateIp.
   */
  public java.lang.String getGateIp() {
    java.lang.Object ref = gateIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gateIp_ = s;
      return s;
    }
  }
  /**
   * <code>string gate_ip = 3;</code>
   * @return The bytes for gateIp.
   */
  public com.google.protobuf.ByteString
      getGateIpBytes() {
    java.lang.Object ref = gateIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gateIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GATE_TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object gateType_;
  /**
   * <code>string gate_type = 4;</code>
   * @return The gateType.
   */
  public java.lang.String getGateType() {
    java.lang.Object ref = gateType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gateType_ = s;
      return s;
    }
  }
  /**
   * <code>string gate_type = 4;</code>
   * @return The bytes for gateType.
   */
  public com.google.protobuf.ByteString
      getGateTypeBytes() {
    java.lang.Object ref = gateType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gateType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GATE_INFO_FIELD_NUMBER = 5;
  private org.network.monitorandcontrol.ag.GateInfo gateInfo_;
  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   * @return Whether the gateInfo field is set.
   */
  public boolean hasGateInfo() {
    return gateInfo_ != null;
  }
  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   * @return The gateInfo.
   */
  public org.network.monitorandcontrol.ag.GateInfo getGateInfo() {
    return gateInfo_ == null ? org.network.monitorandcontrol.ag.GateInfo.getDefaultInstance() : gateInfo_;
  }
  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   */
  public org.network.monitorandcontrol.ag.GateInfoOrBuilder getGateInfoOrBuilder() {
    return getGateInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEquipNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipName_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, equipId_);
    }
    if (!getGateIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gateIp_);
    }
    if (!getGateTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gateType_);
    }
    if (gateInfo_ != null) {
      output.writeMessage(5, getGateInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEquipNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, equipName_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, equipId_);
    }
    if (!getGateIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gateIp_);
    }
    if (!getGateTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gateType_);
    }
    if (gateInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getGateInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.ag.AGDeviceInfo)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.ag.AGDeviceInfo other = (org.network.monitorandcontrol.ag.AGDeviceInfo) obj;

    if (!getEquipName()
        .equals(other.getEquipName())) return false;
    if (!getEquipId()
        .equals(other.getEquipId())) return false;
    if (!getGateIp()
        .equals(other.getGateIp())) return false;
    if (!getGateType()
        .equals(other.getGateType())) return false;
    if (hasGateInfo() != other.hasGateInfo()) return false;
    if (hasGateInfo()) {
      if (!getGateInfo()
          .equals(other.getGateInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EQUIP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEquipName().hashCode();
    hash = (37 * hash) + EQUIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEquipId().hashCode();
    hash = (37 * hash) + GATE_IP_FIELD_NUMBER;
    hash = (53 * hash) + getGateIp().hashCode();
    hash = (37 * hash) + GATE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGateType().hashCode();
    if (hasGateInfo()) {
      hash = (37 * hash) + GATE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getGateInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGDeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.ag.AGDeviceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.monitoring.proto.AGDeviceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.AGDeviceInfo)
      org.network.monitorandcontrol.ag.AGDeviceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGDeviceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGDeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.ag.AGDeviceInfo.class, org.network.monitorandcontrol.ag.AGDeviceInfo.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.ag.AGDeviceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      equipName_ = "";

      equipId_ = "";

      gateIp_ = "";

      gateType_ = "";

      if (gateInfoBuilder_ == null) {
        gateInfo_ = null;
      } else {
        gateInfo_ = null;
        gateInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGDeviceInfo_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGDeviceInfo getDefaultInstanceForType() {
      return org.network.monitorandcontrol.ag.AGDeviceInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGDeviceInfo build() {
      org.network.monitorandcontrol.ag.AGDeviceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGDeviceInfo buildPartial() {
      org.network.monitorandcontrol.ag.AGDeviceInfo result = new org.network.monitorandcontrol.ag.AGDeviceInfo(this);
      result.equipName_ = equipName_;
      result.equipId_ = equipId_;
      result.gateIp_ = gateIp_;
      result.gateType_ = gateType_;
      if (gateInfoBuilder_ == null) {
        result.gateInfo_ = gateInfo_;
      } else {
        result.gateInfo_ = gateInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.ag.AGDeviceInfo) {
        return mergeFrom((org.network.monitorandcontrol.ag.AGDeviceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.ag.AGDeviceInfo other) {
      if (other == org.network.monitorandcontrol.ag.AGDeviceInfo.getDefaultInstance()) return this;
      if (!other.getEquipName().isEmpty()) {
        equipName_ = other.equipName_;
        onChanged();
      }
      if (!other.getEquipId().isEmpty()) {
        equipId_ = other.equipId_;
        onChanged();
      }
      if (!other.getGateIp().isEmpty()) {
        gateIp_ = other.gateIp_;
        onChanged();
      }
      if (!other.getGateType().isEmpty()) {
        gateType_ = other.gateType_;
        onChanged();
      }
      if (other.hasGateInfo()) {
        mergeGateInfo(other.getGateInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.ag.AGDeviceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.ag.AGDeviceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object equipName_ = "";
    /**
     * <code>string equip_name = 1;</code>
     * @return The equipName.
     */
    public java.lang.String getEquipName() {
      java.lang.Object ref = equipName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string equip_name = 1;</code>
     * @return The bytes for equipName.
     */
    public com.google.protobuf.ByteString
        getEquipNameBytes() {
      java.lang.Object ref = equipName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string equip_name = 1;</code>
     * @param value The equipName to set.
     * @return This builder for chaining.
     */
    public Builder setEquipName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      equipName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string equip_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipName() {
      
      equipName_ = getDefaultInstance().getEquipName();
      onChanged();
      return this;
    }
    /**
     * <code>string equip_name = 1;</code>
     * @param value The bytes for equipName to set.
     * @return This builder for chaining.
     */
    public Builder setEquipNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      equipName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object equipId_ = "";
    /**
     * <code>string equip_id = 2;</code>
     * @return The equipId.
     */
    public java.lang.String getEquipId() {
      java.lang.Object ref = equipId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return The bytes for equipId.
     */
    public com.google.protobuf.ByteString
        getEquipIdBytes() {
      java.lang.Object ref = equipId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      equipId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipId() {
      
      equipId_ = getDefaultInstance().getEquipId();
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The bytes for equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      equipId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gateIp_ = "";
    /**
     * <code>string gate_ip = 3;</code>
     * @return The gateIp.
     */
    public java.lang.String getGateIp() {
      java.lang.Object ref = gateIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gateIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gate_ip = 3;</code>
     * @return The bytes for gateIp.
     */
    public com.google.protobuf.ByteString
        getGateIpBytes() {
      java.lang.Object ref = gateIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gateIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gate_ip = 3;</code>
     * @param value The gateIp to set.
     * @return This builder for chaining.
     */
    public Builder setGateIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gateIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gate_ip = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGateIp() {
      
      gateIp_ = getDefaultInstance().getGateIp();
      onChanged();
      return this;
    }
    /**
     * <code>string gate_ip = 3;</code>
     * @param value The bytes for gateIp to set.
     * @return This builder for chaining.
     */
    public Builder setGateIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gateIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gateType_ = "";
    /**
     * <code>string gate_type = 4;</code>
     * @return The gateType.
     */
    public java.lang.String getGateType() {
      java.lang.Object ref = gateType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gateType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gate_type = 4;</code>
     * @return The bytes for gateType.
     */
    public com.google.protobuf.ByteString
        getGateTypeBytes() {
      java.lang.Object ref = gateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gate_type = 4;</code>
     * @param value The gateType to set.
     * @return This builder for chaining.
     */
    public Builder setGateType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gate_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGateType() {
      
      gateType_ = getDefaultInstance().getGateType();
      onChanged();
      return this;
    }
    /**
     * <code>string gate_type = 4;</code>
     * @param value The bytes for gateType to set.
     * @return This builder for chaining.
     */
    public Builder setGateTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gateType_ = value;
      onChanged();
      return this;
    }

    private org.network.monitorandcontrol.ag.GateInfo gateInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.network.monitorandcontrol.ag.GateInfo, org.network.monitorandcontrol.ag.GateInfo.Builder, org.network.monitorandcontrol.ag.GateInfoOrBuilder> gateInfoBuilder_;
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     * @return Whether the gateInfo field is set.
     */
    public boolean hasGateInfo() {
      return gateInfoBuilder_ != null || gateInfo_ != null;
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     * @return The gateInfo.
     */
    public org.network.monitorandcontrol.ag.GateInfo getGateInfo() {
      if (gateInfoBuilder_ == null) {
        return gateInfo_ == null ? org.network.monitorandcontrol.ag.GateInfo.getDefaultInstance() : gateInfo_;
      } else {
        return gateInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public Builder setGateInfo(org.network.monitorandcontrol.ag.GateInfo value) {
      if (gateInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gateInfo_ = value;
        onChanged();
      } else {
        gateInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public Builder setGateInfo(
        org.network.monitorandcontrol.ag.GateInfo.Builder builderForValue) {
      if (gateInfoBuilder_ == null) {
        gateInfo_ = builderForValue.build();
        onChanged();
      } else {
        gateInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public Builder mergeGateInfo(org.network.monitorandcontrol.ag.GateInfo value) {
      if (gateInfoBuilder_ == null) {
        if (gateInfo_ != null) {
          gateInfo_ =
            org.network.monitorandcontrol.ag.GateInfo.newBuilder(gateInfo_).mergeFrom(value).buildPartial();
        } else {
          gateInfo_ = value;
        }
        onChanged();
      } else {
        gateInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public Builder clearGateInfo() {
      if (gateInfoBuilder_ == null) {
        gateInfo_ = null;
        onChanged();
      } else {
        gateInfo_ = null;
        gateInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public org.network.monitorandcontrol.ag.GateInfo.Builder getGateInfoBuilder() {
      
      onChanged();
      return getGateInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    public org.network.monitorandcontrol.ag.GateInfoOrBuilder getGateInfoOrBuilder() {
      if (gateInfoBuilder_ != null) {
        return gateInfoBuilder_.getMessageOrBuilder();
      } else {
        return gateInfo_ == null ?
            org.network.monitorandcontrol.ag.GateInfo.getDefaultInstance() : gateInfo_;
      }
    }
    /**
     * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.network.monitorandcontrol.ag.GateInfo, org.network.monitorandcontrol.ag.GateInfo.Builder, org.network.monitorandcontrol.ag.GateInfoOrBuilder> 
        getGateInfoFieldBuilder() {
      if (gateInfoBuilder_ == null) {
        gateInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.network.monitorandcontrol.ag.GateInfo, org.network.monitorandcontrol.ag.GateInfo.Builder, org.network.monitorandcontrol.ag.GateInfoOrBuilder>(
                getGateInfo(),
                getParentForChildren(),
                isClean());
        gateInfo_ = null;
      }
      return gateInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.AGDeviceInfo)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.AGDeviceInfo)
  private static final org.network.monitorandcontrol.ag.AGDeviceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.ag.AGDeviceInfo();
  }

  public static org.network.monitorandcontrol.ag.AGDeviceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AGDeviceInfo>
      PARSER = new com.google.protobuf.AbstractParser<AGDeviceInfo>() {
    @java.lang.Override
    public AGDeviceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AGDeviceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AGDeviceInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AGDeviceInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.ag.AGDeviceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

