// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

public interface AGDeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.AGDeviceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string equip_name = 1;</code>
   * @return The equipName.
   */
  java.lang.String getEquipName();
  /**
   * <code>string equip_name = 1;</code>
   * @return The bytes for equipName.
   */
  com.google.protobuf.ByteString
      getEquipNameBytes();

  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  java.lang.String getEquipId();
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  com.google.protobuf.ByteString
      getEquipIdBytes();

  /**
   * <code>string gate_ip = 3;</code>
   * @return The gateIp.
   */
  java.lang.String getGateIp();
  /**
   * <code>string gate_ip = 3;</code>
   * @return The bytes for gateIp.
   */
  com.google.protobuf.ByteString
      getGateIpBytes();

  /**
   * <code>string gate_type = 4;</code>
   * @return The gateType.
   */
  java.lang.String getGateType();
  /**
   * <code>string gate_type = 4;</code>
   * @return The bytes for gateType.
   */
  com.google.protobuf.ByteString
      getGateTypeBytes();

  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   * @return Whether the gateInfo field is set.
   */
  boolean hasGateInfo();
  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   * @return The gateInfo.
   */
  org.network.monitorandcontrol.ag.GateInfo getGateInfo();
  /**
   * <code>.org.monitoring.proto.GateInfo gate_info = 5;</code>
   */
  org.network.monitorandcontrol.ag.GateInfoOrBuilder getGateInfoOrBuilder();
}
