// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG_enums.proto

package org.network.monitorandcontrol.ag;

public final class AGEnums {
  private AGEnums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016AG_enums.proto\022\024org.monitoring.proto*4" +
      "\n\tAisleMode\022\t\n\005ENTRY\020\000\022\010\n\004EXIT\020\001\022\022\n\016BI_D" +
      "IRECTIONAL\020\002*2\n\010FlapMode\022\021\n\rNORMALLY_OPE" +
      "N\020\000\022\023\n\017NORMALLY_CLOSED\020\001B$\n org.network." +
      "monitorandcontrol.agP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
