// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

public interface AGModeControlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.AGModeControl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.monitoring.proto.OperationMode operation_mode = 1;</code>
   * @return The enum numeric value on the wire for operationMode.
   */
  int getOperationModeValue();
  /**
   * <code>.org.monitoring.proto.OperationMode operation_mode = 1;</code>
   * @return The operationMode.
   */
  org.network.monitorandcontrol.OperationMode getOperationMode();

  /**
   * <code>.org.monitoring.proto.AisleMode aisle_mode = 2;</code>
   * @return The enum numeric value on the wire for aisleMode.
   */
  int getAisleModeValue();
  /**
   * <code>.org.monitoring.proto.AisleMode aisle_mode = 2;</code>
   * @return The aisleMode.
   */
  org.network.monitorandcontrol.ag.AisleMode getAisleMode();

  /**
   * <code>.org.monitoring.proto.FlapMode flap_mode = 3;</code>
   * @return The enum numeric value on the wire for flapMode.
   */
  int getFlapModeValue();
  /**
   * <code>.org.monitoring.proto.FlapMode flap_mode = 3;</code>
   * @return The flapMode.
   */
  org.network.monitorandcontrol.ag.FlapMode getFlapMode();

  /**
   * <code>.org.monitoring.proto.SpecialMode special_mode = 4;</code>
   * @return The enum numeric value on the wire for specialMode.
   */
  int getSpecialModeValue();
  /**
   * <code>.org.monitoring.proto.SpecialMode special_mode = 4;</code>
   * @return The specialMode.
   */
  org.network.monitorandcontrol.SpecialMode getSpecialMode();
}
