// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

public interface AGPeripheralStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.AGPeripheralStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool scu_connected = 1;</code>
   * @return The scuConnected.
   */
  boolean getScuConnected();

  /**
   * <code>bool ccu_connected = 2;</code>
   * @return The ccuConnected.
   */
  boolean getCcuConnected();

  /**
   * <code>bool gcu_connected = 3;</code>
   * @return The gcuConnected.
   */
  boolean getGcuConnected();

  /**
   * <code>bool reader1_connected = 4;</code>
   * @return The reader1Connected.
   */
  boolean getReader1Connected();

  /**
   * <code>bool reader2_connected = 5;</code>
   * @return The reader2Connected.
   */
  boolean getReader2Connected();

  /**
   * <code>bool scanner1_connected = 6;</code>
   * @return The scanner1Connected.
   */
  boolean getScanner1Connected();

  /**
   * <code>bool scanner2_connected = 7;</code>
   * @return The scanner2Connected.
   */
  boolean getScanner2Connected();

  /**
   * <code>bool ups_connected = 8;</code>
   * @return The upsConnected.
   */
  boolean getUpsConnected();

  /**
   * <code>repeated string alarms = 9;</code>
   * @return A list containing the alarms.
   */
  java.util.List<java.lang.String>
      getAlarmsList();
  /**
   * <code>repeated string alarms = 9;</code>
   * @return The count of alarms.
   */
  int getAlarmsCount();
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the element to return.
   * @return The alarms at the given index.
   */
  java.lang.String getAlarms(int index);
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the alarms at the given index.
   */
  com.google.protobuf.ByteString
      getAlarmsBytes(int index);
}
