// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

/**
 * <pre>
 *Monitoring Protocols
 *AGPeripheralStatus give information about the peripherals connection or disconnection
 *request_type  - 2
 * </pre>
 *
 * Protobuf type {@code org.monitoring.proto.AGPeripheralStatus}
 */
public  final class AGPeripheralStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.AGPeripheralStatus)
    AGPeripheralStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AGPeripheralStatus.newBuilder() to construct.
  private AGPeripheralStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AGPeripheralStatus() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AGPeripheralStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AGPeripheralStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            scuConnected_ = input.readBool();
            break;
          }
          case 16: {

            ccuConnected_ = input.readBool();
            break;
          }
          case 24: {

            gcuConnected_ = input.readBool();
            break;
          }
          case 32: {

            reader1Connected_ = input.readBool();
            break;
          }
          case 40: {

            reader2Connected_ = input.readBool();
            break;
          }
          case 48: {

            scanner1Connected_ = input.readBool();
            break;
          }
          case 56: {

            scanner2Connected_ = input.readBool();
            break;
          }
          case 64: {

            upsConnected_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGPeripheralStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGPeripheralStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.ag.AGPeripheralStatus.class, org.network.monitorandcontrol.ag.AGPeripheralStatus.Builder.class);
  }

  public static final int SCU_CONNECTED_FIELD_NUMBER = 1;
  private boolean scuConnected_;
  /**
   * <code>bool scu_connected = 1;</code>
   * @return The scuConnected.
   */
  public boolean getScuConnected() {
    return scuConnected_;
  }

  public static final int CCU_CONNECTED_FIELD_NUMBER = 2;
  private boolean ccuConnected_;
  /**
   * <code>bool ccu_connected = 2;</code>
   * @return The ccuConnected.
   */
  public boolean getCcuConnected() {
    return ccuConnected_;
  }

  public static final int GCU_CONNECTED_FIELD_NUMBER = 3;
  private boolean gcuConnected_;
  /**
   * <code>bool gcu_connected = 3;</code>
   * @return The gcuConnected.
   */
  public boolean getGcuConnected() {
    return gcuConnected_;
  }

  public static final int READER1_CONNECTED_FIELD_NUMBER = 4;
  private boolean reader1Connected_;
  /**
   * <code>bool reader1_connected = 4;</code>
   * @return The reader1Connected.
   */
  public boolean getReader1Connected() {
    return reader1Connected_;
  }

  public static final int READER2_CONNECTED_FIELD_NUMBER = 5;
  private boolean reader2Connected_;
  /**
   * <code>bool reader2_connected = 5;</code>
   * @return The reader2Connected.
   */
  public boolean getReader2Connected() {
    return reader2Connected_;
  }

  public static final int SCANNER1_CONNECTED_FIELD_NUMBER = 6;
  private boolean scanner1Connected_;
  /**
   * <code>bool scanner1_connected = 6;</code>
   * @return The scanner1Connected.
   */
  public boolean getScanner1Connected() {
    return scanner1Connected_;
  }

  public static final int SCANNER2_CONNECTED_FIELD_NUMBER = 7;
  private boolean scanner2Connected_;
  /**
   * <code>bool scanner2_connected = 7;</code>
   * @return The scanner2Connected.
   */
  public boolean getScanner2Connected() {
    return scanner2Connected_;
  }

  public static final int UPS_CONNECTED_FIELD_NUMBER = 8;
  private boolean upsConnected_;
  /**
   * <code>bool ups_connected = 8;</code>
   * @return The upsConnected.
   */
  public boolean getUpsConnected() {
    return upsConnected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scuConnected_ != false) {
      output.writeBool(1, scuConnected_);
    }
    if (ccuConnected_ != false) {
      output.writeBool(2, ccuConnected_);
    }
    if (gcuConnected_ != false) {
      output.writeBool(3, gcuConnected_);
    }
    if (reader1Connected_ != false) {
      output.writeBool(4, reader1Connected_);
    }
    if (reader2Connected_ != false) {
      output.writeBool(5, reader2Connected_);
    }
    if (scanner1Connected_ != false) {
      output.writeBool(6, scanner1Connected_);
    }
    if (scanner2Connected_ != false) {
      output.writeBool(7, scanner2Connected_);
    }
    if (upsConnected_ != false) {
      output.writeBool(8, upsConnected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scuConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, scuConnected_);
    }
    if (ccuConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ccuConnected_);
    }
    if (gcuConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, gcuConnected_);
    }
    if (reader1Connected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, reader1Connected_);
    }
    if (reader2Connected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, reader2Connected_);
    }
    if (scanner1Connected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, scanner1Connected_);
    }
    if (scanner2Connected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, scanner2Connected_);
    }
    if (upsConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, upsConnected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.ag.AGPeripheralStatus)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.ag.AGPeripheralStatus other = (org.network.monitorandcontrol.ag.AGPeripheralStatus) obj;

    if (getScuConnected()
        != other.getScuConnected()) return false;
    if (getCcuConnected()
        != other.getCcuConnected()) return false;
    if (getGcuConnected()
        != other.getGcuConnected()) return false;
    if (getReader1Connected()
        != other.getReader1Connected()) return false;
    if (getReader2Connected()
        != other.getReader2Connected()) return false;
    if (getScanner1Connected()
        != other.getScanner1Connected()) return false;
    if (getScanner2Connected()
        != other.getScanner2Connected()) return false;
    if (getUpsConnected()
        != other.getUpsConnected()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getScuConnected());
    hash = (37 * hash) + CCU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCcuConnected());
    hash = (37 * hash) + GCU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGcuConnected());
    hash = (37 * hash) + READER1_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReader1Connected());
    hash = (37 * hash) + READER2_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReader2Connected());
    hash = (37 * hash) + SCANNER1_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getScanner1Connected());
    hash = (37 * hash) + SCANNER2_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getScanner2Connected());
    hash = (37 * hash) + UPS_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUpsConnected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.AGPeripheralStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.ag.AGPeripheralStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Monitoring Protocols
   *AGPeripheralStatus give information about the peripherals connection or disconnection
   *request_type  - 2
   * </pre>
   *
   * Protobuf type {@code org.monitoring.proto.AGPeripheralStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.AGPeripheralStatus)
      org.network.monitorandcontrol.ag.AGPeripheralStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGPeripheralStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGPeripheralStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.ag.AGPeripheralStatus.class, org.network.monitorandcontrol.ag.AGPeripheralStatus.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.ag.AGPeripheralStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      scuConnected_ = false;

      ccuConnected_ = false;

      gcuConnected_ = false;

      reader1Connected_ = false;

      reader2Connected_ = false;

      scanner1Connected_ = false;

      scanner2Connected_ = false;

      upsConnected_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_AGPeripheralStatus_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGPeripheralStatus getDefaultInstanceForType() {
      return org.network.monitorandcontrol.ag.AGPeripheralStatus.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGPeripheralStatus build() {
      org.network.monitorandcontrol.ag.AGPeripheralStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.AGPeripheralStatus buildPartial() {
      org.network.monitorandcontrol.ag.AGPeripheralStatus result = new org.network.monitorandcontrol.ag.AGPeripheralStatus(this);
      result.scuConnected_ = scuConnected_;
      result.ccuConnected_ = ccuConnected_;
      result.gcuConnected_ = gcuConnected_;
      result.reader1Connected_ = reader1Connected_;
      result.reader2Connected_ = reader2Connected_;
      result.scanner1Connected_ = scanner1Connected_;
      result.scanner2Connected_ = scanner2Connected_;
      result.upsConnected_ = upsConnected_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.ag.AGPeripheralStatus) {
        return mergeFrom((org.network.monitorandcontrol.ag.AGPeripheralStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.ag.AGPeripheralStatus other) {
      if (other == org.network.monitorandcontrol.ag.AGPeripheralStatus.getDefaultInstance()) return this;
      if (other.getScuConnected() != false) {
        setScuConnected(other.getScuConnected());
      }
      if (other.getCcuConnected() != false) {
        setCcuConnected(other.getCcuConnected());
      }
      if (other.getGcuConnected() != false) {
        setGcuConnected(other.getGcuConnected());
      }
      if (other.getReader1Connected() != false) {
        setReader1Connected(other.getReader1Connected());
      }
      if (other.getReader2Connected() != false) {
        setReader2Connected(other.getReader2Connected());
      }
      if (other.getScanner1Connected() != false) {
        setScanner1Connected(other.getScanner1Connected());
      }
      if (other.getScanner2Connected() != false) {
        setScanner2Connected(other.getScanner2Connected());
      }
      if (other.getUpsConnected() != false) {
        setUpsConnected(other.getUpsConnected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.ag.AGPeripheralStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.ag.AGPeripheralStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean scuConnected_ ;
    /**
     * <code>bool scu_connected = 1;</code>
     * @return The scuConnected.
     */
    public boolean getScuConnected() {
      return scuConnected_;
    }
    /**
     * <code>bool scu_connected = 1;</code>
     * @param value The scuConnected to set.
     * @return This builder for chaining.
     */
    public Builder setScuConnected(boolean value) {
      
      scuConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool scu_connected = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScuConnected() {
      
      scuConnected_ = false;
      onChanged();
      return this;
    }

    private boolean ccuConnected_ ;
    /**
     * <code>bool ccu_connected = 2;</code>
     * @return The ccuConnected.
     */
    public boolean getCcuConnected() {
      return ccuConnected_;
    }
    /**
     * <code>bool ccu_connected = 2;</code>
     * @param value The ccuConnected to set.
     * @return This builder for chaining.
     */
    public Builder setCcuConnected(boolean value) {
      
      ccuConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ccu_connected = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCcuConnected() {
      
      ccuConnected_ = false;
      onChanged();
      return this;
    }

    private boolean gcuConnected_ ;
    /**
     * <code>bool gcu_connected = 3;</code>
     * @return The gcuConnected.
     */
    public boolean getGcuConnected() {
      return gcuConnected_;
    }
    /**
     * <code>bool gcu_connected = 3;</code>
     * @param value The gcuConnected to set.
     * @return This builder for chaining.
     */
    public Builder setGcuConnected(boolean value) {
      
      gcuConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool gcu_connected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGcuConnected() {
      
      gcuConnected_ = false;
      onChanged();
      return this;
    }

    private boolean reader1Connected_ ;
    /**
     * <code>bool reader1_connected = 4;</code>
     * @return The reader1Connected.
     */
    public boolean getReader1Connected() {
      return reader1Connected_;
    }
    /**
     * <code>bool reader1_connected = 4;</code>
     * @param value The reader1Connected to set.
     * @return This builder for chaining.
     */
    public Builder setReader1Connected(boolean value) {
      
      reader1Connected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool reader1_connected = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReader1Connected() {
      
      reader1Connected_ = false;
      onChanged();
      return this;
    }

    private boolean reader2Connected_ ;
    /**
     * <code>bool reader2_connected = 5;</code>
     * @return The reader2Connected.
     */
    public boolean getReader2Connected() {
      return reader2Connected_;
    }
    /**
     * <code>bool reader2_connected = 5;</code>
     * @param value The reader2Connected to set.
     * @return This builder for chaining.
     */
    public Builder setReader2Connected(boolean value) {
      
      reader2Connected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool reader2_connected = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReader2Connected() {
      
      reader2Connected_ = false;
      onChanged();
      return this;
    }

    private boolean scanner1Connected_ ;
    /**
     * <code>bool scanner1_connected = 6;</code>
     * @return The scanner1Connected.
     */
    public boolean getScanner1Connected() {
      return scanner1Connected_;
    }
    /**
     * <code>bool scanner1_connected = 6;</code>
     * @param value The scanner1Connected to set.
     * @return This builder for chaining.
     */
    public Builder setScanner1Connected(boolean value) {
      
      scanner1Connected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool scanner1_connected = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanner1Connected() {
      
      scanner1Connected_ = false;
      onChanged();
      return this;
    }

    private boolean scanner2Connected_ ;
    /**
     * <code>bool scanner2_connected = 7;</code>
     * @return The scanner2Connected.
     */
    public boolean getScanner2Connected() {
      return scanner2Connected_;
    }
    /**
     * <code>bool scanner2_connected = 7;</code>
     * @param value The scanner2Connected to set.
     * @return This builder for chaining.
     */
    public Builder setScanner2Connected(boolean value) {
      
      scanner2Connected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool scanner2_connected = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanner2Connected() {
      
      scanner2Connected_ = false;
      onChanged();
      return this;
    }

    private boolean upsConnected_ ;
    /**
     * <code>bool ups_connected = 8;</code>
     * @return The upsConnected.
     */
    public boolean getUpsConnected() {
      return upsConnected_;
    }
    /**
     * <code>bool ups_connected = 8;</code>
     * @param value The upsConnected to set.
     * @return This builder for chaining.
     */
    public Builder setUpsConnected(boolean value) {
      
      upsConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ups_connected = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpsConnected() {
      
      upsConnected_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.AGPeripheralStatus)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.AGPeripheralStatus)
  private static final org.network.monitorandcontrol.ag.AGPeripheralStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.ag.AGPeripheralStatus();
  }

  public static org.network.monitorandcontrol.ag.AGPeripheralStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AGPeripheralStatus>
      PARSER = new com.google.protobuf.AbstractParser<AGPeripheralStatus>() {
    @java.lang.Override
    public AGPeripheralStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AGPeripheralStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AGPeripheralStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AGPeripheralStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.ag.AGPeripheralStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

