// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

public interface AGRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.AGRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 uid = 2;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>int32 request_type = 3;</code>
   * @return The requestType.
   */
  int getRequestType();

  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return Whether the requestData field is set.
   */
  boolean hasRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return The requestData.
   */
  com.google.protobuf.Any getRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getRequestDataOrBuilder();
}
