// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

public interface AGVersionCheckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.AGVersionCheck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fare_table = 1;</code>
   * @return The fareTable.
   */
  java.lang.String getFareTable();
  /**
   * <code>string fare_table = 1;</code>
   * @return The bytes for fareTable.
   */
  com.google.protobuf.ByteString
      getFareTableBytes();

  /**
   * <code>string users = 2;</code>
   * @return The users.
   */
  java.lang.String getUsers();
  /**
   * <code>string users = 2;</code>
   * @return The bytes for users.
   */
  com.google.protobuf.ByteString
      getUsersBytes();

  /**
   * <code>string ag_software = 3;</code>
   * @return The agSoftware.
   */
  java.lang.String getAgSoftware();
  /**
   * <code>string ag_software = 3;</code>
   * @return The bytes for agSoftware.
   */
  com.google.protobuf.ByteString
      getAgSoftwareBytes();

  /**
   * <code>string blacklist = 4;</code>
   * @return The blacklist.
   */
  java.lang.String getBlacklist();
  /**
   * <code>string blacklist = 4;</code>
   * @return The bytes for blacklist.
   */
  com.google.protobuf.ByteString
      getBlacklistBytes();

  /**
   * <code>string calander = 5;</code>
   * @return The calander.
   */
  java.lang.String getCalander();
  /**
   * <code>string calander = 5;</code>
   * @return The bytes for calander.
   */
  com.google.protobuf.ByteString
      getCalanderBytes();

  /**
   * <code>string qr_key = 6;</code>
   * @return The qrKey.
   */
  java.lang.String getQrKey();
  /**
   * <code>string qr_key = 6;</code>
   * @return The bytes for qrKey.
   */
  com.google.protobuf.ByteString
      getQrKeyBytes();

  /**
   * <code>string ticket = 7;</code>
   * @return The ticket.
   */
  java.lang.String getTicket();
  /**
   * <code>string ticket = 7;</code>
   * @return The bytes for ticket.
   */
  com.google.protobuf.ByteString
      getTicketBytes();
}
