// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG_enums.proto

package org.network.monitorandcontrol.ag;

/**
 * Protobuf enum {@code org.monitoring.proto.AisleMode}
 */
public enum AisleMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENTRY = 0;</code>
   */
  ENTRY(0),
  /**
   * <code>EXIT = 1;</code>
   */
  EXIT(1),
  /**
   * <code>BI_DIRECTIONAL = 2;</code>
   */
  BI_DIRECTIONAL(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ENTRY = 0;</code>
   */
  public static final int ENTRY_VALUE = 0;
  /**
   * <code>EXIT = 1;</code>
   */
  public static final int EXIT_VALUE = 1;
  /**
   * <code>BI_DIRECTIONAL = 2;</code>
   */
  public static final int BI_DIRECTIONAL_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AisleMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AisleMode forNumber(int value) {
    switch (value) {
      case 0: return ENTRY;
      case 1: return EXIT;
      case 2: return BI_DIRECTIONAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AisleMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AisleMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AisleMode>() {
          public AisleMode findValueByNumber(int number) {
            return AisleMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.network.monitorandcontrol.ag.AGEnums.getDescriptor().getEnumTypes().get(0);
  }

  private static final AisleMode[] VALUES = values();

  public static AisleMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AisleMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.monitoring.proto.AisleMode)
}

