// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AG.proto

package org.network.monitorandcontrol.ag;

/**
 * <pre>
 *GateInfo is information about modes set in the GCU
 * </pre>
 *
 * Protobuf type {@code org.monitoring.proto.GateInfo}
 */
public  final class GateInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.GateInfo)
    GateInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GateInfo.newBuilder() to construct.
  private GateInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GateInfo() {
    gcuVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GateInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GateInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            gateMode_ = input.readInt32();
            break;
          }
          case 16: {

            passageInfo_ = input.readInt32();
            break;
          }
          case 24: {

            emergencyMode_ = input.readInt32();
            break;
          }
          case 32: {

            maintenanceFlapInfo_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            gcuVersion_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_GateInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_GateInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.ag.GateInfo.class, org.network.monitorandcontrol.ag.GateInfo.Builder.class);
  }

  public static final int GATE_MODE_FIELD_NUMBER = 1;
  private int gateMode_;
  /**
   * <code>int32 gate_mode = 1;</code>
   * @return The gateMode.
   */
  public int getGateMode() {
    return gateMode_;
  }

  public static final int PASSAGE_INFO_FIELD_NUMBER = 2;
  private int passageInfo_;
  /**
   * <code>int32 passage_info = 2;</code>
   * @return The passageInfo.
   */
  public int getPassageInfo() {
    return passageInfo_;
  }

  public static final int EMERGENCY_MODE_FIELD_NUMBER = 3;
  private int emergencyMode_;
  /**
   * <code>int32 emergency_mode = 3;</code>
   * @return The emergencyMode.
   */
  public int getEmergencyMode() {
    return emergencyMode_;
  }

  public static final int MAINTENANCE_FLAP_INFO_FIELD_NUMBER = 4;
  private int maintenanceFlapInfo_;
  /**
   * <code>int32 maintenance_flap_info = 4;</code>
   * @return The maintenanceFlapInfo.
   */
  public int getMaintenanceFlapInfo() {
    return maintenanceFlapInfo_;
  }

  public static final int GCU_VERSION_FIELD_NUMBER = 5;
  private volatile java.lang.Object gcuVersion_;
  /**
   * <code>string gcu_version = 5;</code>
   * @return The gcuVersion.
   */
  public java.lang.String getGcuVersion() {
    java.lang.Object ref = gcuVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gcuVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string gcu_version = 5;</code>
   * @return The bytes for gcuVersion.
   */
  public com.google.protobuf.ByteString
      getGcuVersionBytes() {
    java.lang.Object ref = gcuVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gcuVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (gateMode_ != 0) {
      output.writeInt32(1, gateMode_);
    }
    if (passageInfo_ != 0) {
      output.writeInt32(2, passageInfo_);
    }
    if (emergencyMode_ != 0) {
      output.writeInt32(3, emergencyMode_);
    }
    if (maintenanceFlapInfo_ != 0) {
      output.writeInt32(4, maintenanceFlapInfo_);
    }
    if (!getGcuVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gcuVersion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (gateMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, gateMode_);
    }
    if (passageInfo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, passageInfo_);
    }
    if (emergencyMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, emergencyMode_);
    }
    if (maintenanceFlapInfo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maintenanceFlapInfo_);
    }
    if (!getGcuVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gcuVersion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.ag.GateInfo)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.ag.GateInfo other = (org.network.monitorandcontrol.ag.GateInfo) obj;

    if (getGateMode()
        != other.getGateMode()) return false;
    if (getPassageInfo()
        != other.getPassageInfo()) return false;
    if (getEmergencyMode()
        != other.getEmergencyMode()) return false;
    if (getMaintenanceFlapInfo()
        != other.getMaintenanceFlapInfo()) return false;
    if (!getGcuVersion()
        .equals(other.getGcuVersion())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GATE_MODE_FIELD_NUMBER;
    hash = (53 * hash) + getGateMode();
    hash = (37 * hash) + PASSAGE_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getPassageInfo();
    hash = (37 * hash) + EMERGENCY_MODE_FIELD_NUMBER;
    hash = (53 * hash) + getEmergencyMode();
    hash = (37 * hash) + MAINTENANCE_FLAP_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getMaintenanceFlapInfo();
    hash = (37 * hash) + GCU_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getGcuVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.ag.GateInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.ag.GateInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *GateInfo is information about modes set in the GCU
   * </pre>
   *
   * Protobuf type {@code org.monitoring.proto.GateInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.GateInfo)
      org.network.monitorandcontrol.ag.GateInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_GateInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_GateInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.ag.GateInfo.class, org.network.monitorandcontrol.ag.GateInfo.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.ag.GateInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      gateMode_ = 0;

      passageInfo_ = 0;

      emergencyMode_ = 0;

      maintenanceFlapInfo_ = 0;

      gcuVersion_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.ag.AG.internal_static_org_monitoring_proto_GateInfo_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.GateInfo getDefaultInstanceForType() {
      return org.network.monitorandcontrol.ag.GateInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.GateInfo build() {
      org.network.monitorandcontrol.ag.GateInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.ag.GateInfo buildPartial() {
      org.network.monitorandcontrol.ag.GateInfo result = new org.network.monitorandcontrol.ag.GateInfo(this);
      result.gateMode_ = gateMode_;
      result.passageInfo_ = passageInfo_;
      result.emergencyMode_ = emergencyMode_;
      result.maintenanceFlapInfo_ = maintenanceFlapInfo_;
      result.gcuVersion_ = gcuVersion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.ag.GateInfo) {
        return mergeFrom((org.network.monitorandcontrol.ag.GateInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.ag.GateInfo other) {
      if (other == org.network.monitorandcontrol.ag.GateInfo.getDefaultInstance()) return this;
      if (other.getGateMode() != 0) {
        setGateMode(other.getGateMode());
      }
      if (other.getPassageInfo() != 0) {
        setPassageInfo(other.getPassageInfo());
      }
      if (other.getEmergencyMode() != 0) {
        setEmergencyMode(other.getEmergencyMode());
      }
      if (other.getMaintenanceFlapInfo() != 0) {
        setMaintenanceFlapInfo(other.getMaintenanceFlapInfo());
      }
      if (!other.getGcuVersion().isEmpty()) {
        gcuVersion_ = other.gcuVersion_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.ag.GateInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.ag.GateInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int gateMode_ ;
    /**
     * <code>int32 gate_mode = 1;</code>
     * @return The gateMode.
     */
    public int getGateMode() {
      return gateMode_;
    }
    /**
     * <code>int32 gate_mode = 1;</code>
     * @param value The gateMode to set.
     * @return This builder for chaining.
     */
    public Builder setGateMode(int value) {
      
      gateMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 gate_mode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGateMode() {
      
      gateMode_ = 0;
      onChanged();
      return this;
    }

    private int passageInfo_ ;
    /**
     * <code>int32 passage_info = 2;</code>
     * @return The passageInfo.
     */
    public int getPassageInfo() {
      return passageInfo_;
    }
    /**
     * <code>int32 passage_info = 2;</code>
     * @param value The passageInfo to set.
     * @return This builder for chaining.
     */
    public Builder setPassageInfo(int value) {
      
      passageInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 passage_info = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassageInfo() {
      
      passageInfo_ = 0;
      onChanged();
      return this;
    }

    private int emergencyMode_ ;
    /**
     * <code>int32 emergency_mode = 3;</code>
     * @return The emergencyMode.
     */
    public int getEmergencyMode() {
      return emergencyMode_;
    }
    /**
     * <code>int32 emergency_mode = 3;</code>
     * @param value The emergencyMode to set.
     * @return This builder for chaining.
     */
    public Builder setEmergencyMode(int value) {
      
      emergencyMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 emergency_mode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmergencyMode() {
      
      emergencyMode_ = 0;
      onChanged();
      return this;
    }

    private int maintenanceFlapInfo_ ;
    /**
     * <code>int32 maintenance_flap_info = 4;</code>
     * @return The maintenanceFlapInfo.
     */
    public int getMaintenanceFlapInfo() {
      return maintenanceFlapInfo_;
    }
    /**
     * <code>int32 maintenance_flap_info = 4;</code>
     * @param value The maintenanceFlapInfo to set.
     * @return This builder for chaining.
     */
    public Builder setMaintenanceFlapInfo(int value) {
      
      maintenanceFlapInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maintenance_flap_info = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaintenanceFlapInfo() {
      
      maintenanceFlapInfo_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object gcuVersion_ = "";
    /**
     * <code>string gcu_version = 5;</code>
     * @return The gcuVersion.
     */
    public java.lang.String getGcuVersion() {
      java.lang.Object ref = gcuVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gcuVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gcu_version = 5;</code>
     * @return The bytes for gcuVersion.
     */
    public com.google.protobuf.ByteString
        getGcuVersionBytes() {
      java.lang.Object ref = gcuVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gcuVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gcu_version = 5;</code>
     * @param value The gcuVersion to set.
     * @return This builder for chaining.
     */
    public Builder setGcuVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gcuVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gcu_version = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGcuVersion() {
      
      gcuVersion_ = getDefaultInstance().getGcuVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string gcu_version = 5;</code>
     * @param value The bytes for gcuVersion to set.
     * @return This builder for chaining.
     */
    public Builder setGcuVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gcuVersion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.GateInfo)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.GateInfo)
  private static final org.network.monitorandcontrol.ag.GateInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.ag.GateInfo();
  }

  public static org.network.monitorandcontrol.ag.GateInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GateInfo>
      PARSER = new com.google.protobuf.AbstractParser<GateInfo>() {
    @java.lang.Override
    public GateInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GateInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GateInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GateInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.ag.GateInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

