// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitoringAndControl.proto

package org.network.monitorandcontrol;

/**
 * <pre>
 *request_type - 10
 * </pre>
 *
 * Protobuf type {@code org.monitoring.proto.Alarms}
 */
public  final class Alarms extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.Alarms)
    AlarmsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alarms.newBuilder() to construct.
  private Alarms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Alarms() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Alarms();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Alarms(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              alarms_ = com.google.protobuf.MapField.newMapField(
                  AlarmsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
            alarms__ = input.readMessage(
                AlarmsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            alarms_.getMutableMap().put(
                alarms__.getKey(), alarms__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetAlarms();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.Alarms.class, org.network.monitorandcontrol.Alarms.Builder.class);
  }

  public static final int ALARMS_FIELD_NUMBER = 1;
  private static final class AlarmsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.String>newDefaultInstance(
                org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_AlarmsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.String> alarms_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
  internalGetAlarms() {
    if (alarms_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AlarmsDefaultEntryHolder.defaultEntry);
    }
    return alarms_;
  }

  public int getAlarmsCount() {
    return internalGetAlarms().getMap().size();
  }
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  public boolean containsAlarms(
      int key) {
    
    return internalGetAlarms().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAlarmsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.String> getAlarms() {
    return getAlarmsMap();
  }
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.String> getAlarmsMap() {
    return internalGetAlarms().getMap();
  }
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  public java.lang.String getAlarmsOrDefault(
      int key,
      java.lang.String defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetAlarms().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  public java.lang.String getAlarmsOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetAlarms().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetAlarms(),
        AlarmsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
         : internalGetAlarms().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
      alarms__ = AlarmsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, alarms__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.Alarms)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.Alarms other = (org.network.monitorandcontrol.Alarms) obj;

    if (!internalGetAlarms().equals(
        other.internalGetAlarms())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetAlarms().getMap().isEmpty()) {
      hash = (37 * hash) + ALARMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAlarms().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.Alarms parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.Alarms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.Alarms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.Alarms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.Alarms prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *request_type - 10
   * </pre>
   *
   * Protobuf type {@code org.monitoring.proto.Alarms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.Alarms)
      org.network.monitorandcontrol.AlarmsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAlarms();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableAlarms();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.Alarms.class, org.network.monitorandcontrol.Alarms.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.Alarms.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableAlarms().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.MonitoringAndControl.internal_static_org_monitoring_proto_Alarms_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.Alarms getDefaultInstanceForType() {
      return org.network.monitorandcontrol.Alarms.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.Alarms build() {
      org.network.monitorandcontrol.Alarms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.Alarms buildPartial() {
      org.network.monitorandcontrol.Alarms result = new org.network.monitorandcontrol.Alarms(this);
      int from_bitField0_ = bitField0_;
      result.alarms_ = internalGetAlarms();
      result.alarms_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.Alarms) {
        return mergeFrom((org.network.monitorandcontrol.Alarms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.Alarms other) {
      if (other == org.network.monitorandcontrol.Alarms.getDefaultInstance()) return this;
      internalGetMutableAlarms().mergeFrom(
          other.internalGetAlarms());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.Alarms parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.Alarms) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> alarms_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetAlarms() {
      if (alarms_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AlarmsDefaultEntryHolder.defaultEntry);
      }
      return alarms_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetMutableAlarms() {
      onChanged();;
      if (alarms_ == null) {
        alarms_ = com.google.protobuf.MapField.newMapField(
            AlarmsDefaultEntryHolder.defaultEntry);
      }
      if (!alarms_.isMutable()) {
        alarms_ = alarms_.copy();
      }
      return alarms_;
    }

    public int getAlarmsCount() {
      return internalGetAlarms().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public boolean containsAlarms(
        int key) {
      
      return internalGetAlarms().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAlarmsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getAlarms() {
      return getAlarmsMap();
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getAlarmsMap() {
      return internalGetAlarms().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public java.lang.String getAlarmsOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetAlarms().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public java.lang.String getAlarmsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetAlarms().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAlarms() {
      internalGetMutableAlarms().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public Builder removeAlarms(
        int key) {
      
      internalGetMutableAlarms().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String>
    getMutableAlarms() {
      return internalGetMutableAlarms().getMutableMap();
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */
    public Builder putAlarms(
        int key,
        java.lang.String value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAlarms().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, string&gt; alarms = 1;</code>
     */

    public Builder putAllAlarms(
        java.util.Map<java.lang.Integer, java.lang.String> values) {
      internalGetMutableAlarms().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.Alarms)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.Alarms)
  private static final org.network.monitorandcontrol.Alarms DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.Alarms();
  }

  public static org.network.monitorandcontrol.Alarms getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Alarms>
      PARSER = new com.google.protobuf.AbstractParser<Alarms>() {
    @java.lang.Override
    public Alarms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Alarms(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Alarms> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alarms> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.Alarms getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

