// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitoringAndControl.proto

package org.network.monitorandcontrol;

public interface AlarmsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.Alarms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */
  int getAlarmsCount();
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */
  boolean containsAlarms(
      int key);
  /**
   * Use {@link #getAlarmsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.String>
  getAlarms();
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.String>
  getAlarmsMap();
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  java.lang.String getAlarmsOrDefault(
      int key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;int32, string&gt; alarms = 1;</code>
   */

  java.lang.String getAlarmsOrThrow(
      int key);
}
