// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package org.network.monitorandcontrol;

/**
 * Protobuf enum {@code org.monitoring.proto.CommandType}
 */
public enum CommandType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_COMMAND = 0;</code>
   */
  UNKNOWN_COMMAND(0),
  /**
   * <code>MODE_CONTROL = 1;</code>
   */
  MODE_CONTROL(1),
  /**
   * <code>GET_DEVICE_INFO = 2;</code>
   */
  GET_DEVICE_INFO(2),
  /**
   * <code>GET_PERIPHERAL_STATUS = 3;</code>
   */
  GET_PERIPHERAL_STATUS(3),
  /**
   * <code>GET_DIVICE_VERSIONS = 4;</code>
   */
  GET_DIVICE_VERSIONS(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_COMMAND = 0;</code>
   */
  public static final int UNKNOWN_COMMAND_VALUE = 0;
  /**
   * <code>MODE_CONTROL = 1;</code>
   */
  public static final int MODE_CONTROL_VALUE = 1;
  /**
   * <code>GET_DEVICE_INFO = 2;</code>
   */
  public static final int GET_DEVICE_INFO_VALUE = 2;
  /**
   * <code>GET_PERIPHERAL_STATUS = 3;</code>
   */
  public static final int GET_PERIPHERAL_STATUS_VALUE = 3;
  /**
   * <code>GET_DIVICE_VERSIONS = 4;</code>
   */
  public static final int GET_DIVICE_VERSIONS_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommandType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CommandType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_COMMAND;
      case 1: return MODE_CONTROL;
      case 2: return GET_DEVICE_INFO;
      case 3: return GET_PERIPHERAL_STATUS;
      case 4: return GET_DIVICE_VERSIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommandType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
          public CommandType findValueByNumber(int number) {
            return CommandType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.network.monitorandcontrol.Enums.getDescriptor().getEnumTypes().get(1);
  }

  private static final CommandType[] VALUES = values();

  public static CommandType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CommandType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.monitoring.proto.CommandType)
}

