// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package org.network.monitorandcontrol;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Enums.proto\022\024org.monitoring.proto*}\n\013R" +
      "equestType\022\025\n\021DIVICE_DISCONNECT\020\000\022\017\n\013DEV" +
      "ICE_INFO\020\001\022\025\n\021PERIPHERAL_STATUS\020\002\022\025\n\021PAR" +
      "AMETER_VERSION\020\003\022\n\n\006ALARMS\020\004\022\014\n\010RESPONSE" +
      "\020\005*}\n\013CommandType\022\023\n\017UNKNOWN_COMMAND\020\000\022\020" +
      "\n\014MODE_CONTROL\020\001\022\023\n\017GET_DEVICE_INFO\020\002\022\031\n" +
      "\025GET_PERIPHERAL_STATUS\020\003\022\027\n\023GET_DIVICE_V" +
      "ERSIONS\020\004*N\n\rOperationMode\022\016\n\nIN_SERVICE" +
      "\020\000\022\022\n\016OUT_OF_SERVICE\020\001\022\017\n\013MAINTENANCE\020\002\022" +
      "\010\n\004TEST\020\003*\326\001\n\013SpecialMode\022\021\n\rTIME_OVERRI" +
      "DE\020\000\022\027\n\023ENTRY_EXIT_OVERRIDE\020\001\022\030\n\024EXCESS_" +
      "FARE_OVERRIDE\020\002\022\r\n\tEMERGENCY\020\003\022\026\n\022FARE_B" +
      "YPASS_MODE_1\020\004\022\026\n\022FARE_BYPASS_MODE_2\020\005\022\027" +
      "\n\023STATION_CLOSED_MODE\020\006\022\r\n\tSHIFT_END\020\007\022\r" +
      "\n\tSHUT_DOWN\020\010\022\013\n\007RESTART\020\t*\035\n\nDeviceType" +
      "\022\007\n\003TOM\020\000\022\006\n\002AG\020\001B!\n\035org.network.monitor" +
      "andcontrolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
