// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitoringAndControl.proto

package org.network.monitorandcontrol;

public final class MonitoringAndControl {
  private MonitoringAndControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032MonitoringAndControl.proto\022\024org.monito" +
      "ring.proto\032\tTOM.proto\032\010AG.proto\032\010SC.prot" +
      "o2\232\002\n\021MonitorAndControl\022S\n\010AGStream\022\037.or" +
      "g.monitoring.proto.AGRequest\032 .org.monit" +
      "oring.proto.AGResponse\"\000(\0010\001\022V\n\tTOMStrea" +
      "m\022 .org.monitoring.proto.TOMRequest\032!.or" +
      "g.monitoring.proto.TOMResponse\"\000(\0010\001\022X\n\010" +
      "SCStream\022#.org.monitoring.proto.ConsoleS" +
      "tream\032!.org.monitoring.proto.PushUpdates" +
      "\"\000(\0010\001B!\n\035org.network.monitorandcontrolP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.network.monitorandcontrol.tom.TOM.getDescriptor(),
          org.network.monitorandcontrol.ag.AG.getDescriptor(),
          org.network.monitorandcontrol.scu_console.SC.getDescriptor(),
        });
    org.network.monitorandcontrol.tom.TOM.getDescriptor();
    org.network.monitorandcontrol.ag.AG.getDescriptor();
    org.network.monitorandcontrol.scu_console.SC.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
