// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package org.network.monitorandcontrol;

/**
 * Protobuf enum {@code org.monitoring.proto.OperationMode}
 */
public enum OperationMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IN_SERVICE = 0;</code>
   */
  IN_SERVICE(0),
  /**
   * <code>OUT_OF_SERVICE = 1;</code>
   */
  OUT_OF_SERVICE(1),
  /**
   * <code>MAINTENANCE = 2;</code>
   */
  MAINTENANCE(2),
  /**
   * <code>TEST = 3;</code>
   */
  TEST(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IN_SERVICE = 0;</code>
   */
  public static final int IN_SERVICE_VALUE = 0;
  /**
   * <code>OUT_OF_SERVICE = 1;</code>
   */
  public static final int OUT_OF_SERVICE_VALUE = 1;
  /**
   * <code>MAINTENANCE = 2;</code>
   */
  public static final int MAINTENANCE_VALUE = 2;
  /**
   * <code>TEST = 3;</code>
   */
  public static final int TEST_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperationMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OperationMode forNumber(int value) {
    switch (value) {
      case 0: return IN_SERVICE;
      case 1: return OUT_OF_SERVICE;
      case 2: return MAINTENANCE;
      case 3: return TEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperationMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperationMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationMode>() {
          public OperationMode findValueByNumber(int number) {
            return OperationMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.network.monitorandcontrol.Enums.getDescriptor().getEnumTypes().get(2);
  }

  private static final OperationMode[] VALUES = values();

  public static OperationMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperationMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.monitoring.proto.OperationMode)
}

