// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package org.network.monitorandcontrol;

/**
 * Protobuf enum {@code org.monitoring.proto.RequestType}
 */
public enum RequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DIVICE_DISCONNECT = 0;</code>
   */
  DIVICE_DISCONNECT(0),
  /**
   * <code>DEVICE_INFO = 1;</code>
   */
  DEVICE_INFO(1),
  /**
   * <code>PERIPHERAL_STATUS = 2;</code>
   */
  PERIPHERAL_STATUS(2),
  /**
   * <code>PARAMETER_VERSION = 3;</code>
   */
  PARAMETER_VERSION(3),
  /**
   * <code>ALARMS = 4;</code>
   */
  ALARMS(4),
  /**
   * <code>RESPONSE = 5;</code>
   */
  RESPONSE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DIVICE_DISCONNECT = 0;</code>
   */
  public static final int DIVICE_DISCONNECT_VALUE = 0;
  /**
   * <code>DEVICE_INFO = 1;</code>
   */
  public static final int DEVICE_INFO_VALUE = 1;
  /**
   * <code>PERIPHERAL_STATUS = 2;</code>
   */
  public static final int PERIPHERAL_STATUS_VALUE = 2;
  /**
   * <code>PARAMETER_VERSION = 3;</code>
   */
  public static final int PARAMETER_VERSION_VALUE = 3;
  /**
   * <code>ALARMS = 4;</code>
   */
  public static final int ALARMS_VALUE = 4;
  /**
   * <code>RESPONSE = 5;</code>
   */
  public static final int RESPONSE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RequestType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RequestType forNumber(int value) {
    switch (value) {
      case 0: return DIVICE_DISCONNECT;
      case 1: return DEVICE_INFO;
      case 2: return PERIPHERAL_STATUS;
      case 3: return PARAMETER_VERSION;
      case 4: return ALARMS;
      case 5: return RESPONSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
          public RequestType findValueByNumber(int number) {
            return RequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.network.monitorandcontrol.Enums.getDescriptor().getEnumTypes().get(0);
  }

  private static final RequestType[] VALUES = values();

  public static RequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.monitoring.proto.RequestType)
}

