// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public final class TOM {
  private TOM() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_TOMRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_TOMRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_TOMResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_TOMResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_TOMVersionCheck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_TOMVersionCheck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_TOMPeripheralStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_TOMDeviceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tTOM.proto\022\024org.monitoring.proto\032\031googl" +
      "e/protobuf/any.proto\"g\n\nTOMRequest\022\n\n\002ip" +
      "\030\001 \001(\t\022\013\n\003uid\030\002 \001(\005\022\024\n\014request_type\030\003 \001(" +
      "\005\022*\n\014request_data\030\004 \001(\0132\024.google.protobu" +
      "f.Any\"a\n\013TOMResponse\022\023\n\013status_code\030\001 \001(" +
      "\005\022\021\n\terror_msg\030\002 \001(\t\022*\n\014request_data\030\003 \001" +
      "(\0132\024.google.protobuf.Any\"\217\001\n\017TOMVersionC" +
      "heck\022\022\n\nfare_table\030\001 \001(\t\022\r\n\005users\030\002 \001(\t\022" +
      "\024\n\014tom_software\030\003 \001(\t\022\021\n\tblacklist\030\004 \001(\t" +
      "\022\020\n\010calander\030\005 \001(\t\022\016\n\006qr_key\030\006 \001(\t\022\016\n\006ti" +
      "cket\030\007 \001(\t\"\203\002\n\023TOMPeripheralStatus\022\025\n\rsc" +
      "u_connected\030\001 \001(\010\022\025\n\rccu_connected\030\002 \001(\010" +
      "\022\030\n\020reader_connected\030\003 \001(\010\022\031\n\021scanner_co" +
      "nnected\030\004 \001(\010\022 \n\030ticket_printer_connecte" +
      "d\030\005 \001(\010\022!\n\031receipt_printer_connected\030\006 \001" +
      "(\010\022\025\n\rpdu_connected\030\007 \001(\010\022\035\n\025cash_drawer" +
      "_connected\030\010 \001(\010\022\016\n\006alarms\030\t \003(\t\"{\n\rTOMD" +
      "eviceInfo\022\022\n\nequip_name\030\001 \001(\t\022\020\n\010equip_i" +
      "d\030\002 \001(\t\022\031\n\021scu_last_txn_sync\030\003 \001(\t\022\031\n\021cc" +
      "u_last_txn_sync\030\004 \001(\t\022\016\n\006tom_ip\030\005 \001(\tB%\n" +
      "!org.network.monitorandcontrol.tomP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_org_monitoring_proto_TOMRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_monitoring_proto_TOMRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_TOMRequest_descriptor,
        new java.lang.String[] { "Ip", "Uid", "RequestType", "RequestData", });
    internal_static_org_monitoring_proto_TOMResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_monitoring_proto_TOMResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_TOMResponse_descriptor,
        new java.lang.String[] { "StatusCode", "ErrorMsg", "RequestData", });
    internal_static_org_monitoring_proto_TOMVersionCheck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_monitoring_proto_TOMVersionCheck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_TOMVersionCheck_descriptor,
        new java.lang.String[] { "FareTable", "Users", "TomSoftware", "Blacklist", "Calander", "QrKey", "Ticket", });
    internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_monitoring_proto_TOMPeripheralStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor,
        new java.lang.String[] { "ScuConnected", "CcuConnected", "ReaderConnected", "ScannerConnected", "TicketPrinterConnected", "ReceiptPrinterConnected", "PduConnected", "CashDrawerConnected", "Alarms", });
    internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_monitoring_proto_TOMDeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor,
        new java.lang.String[] { "EquipName", "EquipId", "ScuLastTxnSync", "CcuLastTxnSync", "TomIp", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
