// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public interface TOMDeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.TOMDeviceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string equip_name = 1;</code>
   * @return The equipName.
   */
  java.lang.String getEquipName();
  /**
   * <code>string equip_name = 1;</code>
   * @return The bytes for equipName.
   */
  com.google.protobuf.ByteString
      getEquipNameBytes();

  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  java.lang.String getEquipId();
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  com.google.protobuf.ByteString
      getEquipIdBytes();

  /**
   * <code>string tom_ip = 3;</code>
   * @return The tomIp.
   */
  java.lang.String getTomIp();
  /**
   * <code>string tom_ip = 3;</code>
   * @return The bytes for tomIp.
   */
  com.google.protobuf.ByteString
      getTomIpBytes();

  /**
   * <code>string device_type = 4;</code>
   * @return The deviceType.
   */
  java.lang.String getDeviceType();
  /**
   * <code>string device_type = 4;</code>
   * @return The bytes for deviceType.
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();
}
