// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

/**
 * Protobuf type {@code org.monitoring.proto.TOMDeviceInfo}
 */
public  final class TOMDeviceInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.TOMDeviceInfo)
    TOMDeviceInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TOMDeviceInfo.newBuilder() to construct.
  private TOMDeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TOMDeviceInfo() {
    equipName_ = "";
    equipId_ = "";
    scuLastTxnSync_ = "";
    ccuLastTxnSync_ = "";
    tomIp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TOMDeviceInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TOMDeviceInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            equipName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            equipId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            scuLastTxnSync_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ccuLastTxnSync_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            tomIp_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMDeviceInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.tom.TOMDeviceInfo.class, org.network.monitorandcontrol.tom.TOMDeviceInfo.Builder.class);
  }

  public static final int EQUIP_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object equipName_;
  /**
   * <code>string equip_name = 1;</code>
   * @return The equipName.
   */
  public java.lang.String getEquipName() {
    java.lang.Object ref = equipName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      equipName_ = s;
      return s;
    }
  }
  /**
   * <code>string equip_name = 1;</code>
   * @return The bytes for equipName.
   */
  public com.google.protobuf.ByteString
      getEquipNameBytes() {
    java.lang.Object ref = equipName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      equipName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EQUIP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object equipId_;
  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  public java.lang.String getEquipId() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      equipId_ = s;
      return s;
    }
  }
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  public com.google.protobuf.ByteString
      getEquipIdBytes() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      equipId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCU_LAST_TXN_SYNC_FIELD_NUMBER = 3;
  private volatile java.lang.Object scuLastTxnSync_;
  /**
   * <pre>
   *colon seperated last_txn:last_sync
   * </pre>
   *
   * <code>string scu_last_txn_sync = 3;</code>
   * @return The scuLastTxnSync.
   */
  public java.lang.String getScuLastTxnSync() {
    java.lang.Object ref = scuLastTxnSync_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scuLastTxnSync_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *colon seperated last_txn:last_sync
   * </pre>
   *
   * <code>string scu_last_txn_sync = 3;</code>
   * @return The bytes for scuLastTxnSync.
   */
  public com.google.protobuf.ByteString
      getScuLastTxnSyncBytes() {
    java.lang.Object ref = scuLastTxnSync_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scuLastTxnSync_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CCU_LAST_TXN_SYNC_FIELD_NUMBER = 4;
  private volatile java.lang.Object ccuLastTxnSync_;
  /**
   * <pre>
   *colon seperated last_txn:last_sync
   * </pre>
   *
   * <code>string ccu_last_txn_sync = 4;</code>
   * @return The ccuLastTxnSync.
   */
  public java.lang.String getCcuLastTxnSync() {
    java.lang.Object ref = ccuLastTxnSync_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ccuLastTxnSync_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *colon seperated last_txn:last_sync
   * </pre>
   *
   * <code>string ccu_last_txn_sync = 4;</code>
   * @return The bytes for ccuLastTxnSync.
   */
  public com.google.protobuf.ByteString
      getCcuLastTxnSyncBytes() {
    java.lang.Object ref = ccuLastTxnSync_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ccuLastTxnSync_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOM_IP_FIELD_NUMBER = 5;
  private volatile java.lang.Object tomIp_;
  /**
   * <code>string tom_ip = 5;</code>
   * @return The tomIp.
   */
  public java.lang.String getTomIp() {
    java.lang.Object ref = tomIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tomIp_ = s;
      return s;
    }
  }
  /**
   * <code>string tom_ip = 5;</code>
   * @return The bytes for tomIp.
   */
  public com.google.protobuf.ByteString
      getTomIpBytes() {
    java.lang.Object ref = tomIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tomIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEquipNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipName_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, equipId_);
    }
    if (!getScuLastTxnSyncBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, scuLastTxnSync_);
    }
    if (!getCcuLastTxnSyncBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ccuLastTxnSync_);
    }
    if (!getTomIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tomIp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEquipNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, equipName_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, equipId_);
    }
    if (!getScuLastTxnSyncBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, scuLastTxnSync_);
    }
    if (!getCcuLastTxnSyncBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ccuLastTxnSync_);
    }
    if (!getTomIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tomIp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.tom.TOMDeviceInfo)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.tom.TOMDeviceInfo other = (org.network.monitorandcontrol.tom.TOMDeviceInfo) obj;

    if (!getEquipName()
        .equals(other.getEquipName())) return false;
    if (!getEquipId()
        .equals(other.getEquipId())) return false;
    if (!getScuLastTxnSync()
        .equals(other.getScuLastTxnSync())) return false;
    if (!getCcuLastTxnSync()
        .equals(other.getCcuLastTxnSync())) return false;
    if (!getTomIp()
        .equals(other.getTomIp())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EQUIP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEquipName().hashCode();
    hash = (37 * hash) + EQUIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEquipId().hashCode();
    hash = (37 * hash) + SCU_LAST_TXN_SYNC_FIELD_NUMBER;
    hash = (53 * hash) + getScuLastTxnSync().hashCode();
    hash = (37 * hash) + CCU_LAST_TXN_SYNC_FIELD_NUMBER;
    hash = (53 * hash) + getCcuLastTxnSync().hashCode();
    hash = (37 * hash) + TOM_IP_FIELD_NUMBER;
    hash = (53 * hash) + getTomIp().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMDeviceInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.tom.TOMDeviceInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.monitoring.proto.TOMDeviceInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.TOMDeviceInfo)
      org.network.monitorandcontrol.tom.TOMDeviceInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMDeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.tom.TOMDeviceInfo.class, org.network.monitorandcontrol.tom.TOMDeviceInfo.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.tom.TOMDeviceInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      equipName_ = "";

      equipId_ = "";

      scuLastTxnSync_ = "";

      ccuLastTxnSync_ = "";

      tomIp_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMDeviceInfo_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMDeviceInfo getDefaultInstanceForType() {
      return org.network.monitorandcontrol.tom.TOMDeviceInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMDeviceInfo build() {
      org.network.monitorandcontrol.tom.TOMDeviceInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMDeviceInfo buildPartial() {
      org.network.monitorandcontrol.tom.TOMDeviceInfo result = new org.network.monitorandcontrol.tom.TOMDeviceInfo(this);
      result.equipName_ = equipName_;
      result.equipId_ = equipId_;
      result.scuLastTxnSync_ = scuLastTxnSync_;
      result.ccuLastTxnSync_ = ccuLastTxnSync_;
      result.tomIp_ = tomIp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.tom.TOMDeviceInfo) {
        return mergeFrom((org.network.monitorandcontrol.tom.TOMDeviceInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.tom.TOMDeviceInfo other) {
      if (other == org.network.monitorandcontrol.tom.TOMDeviceInfo.getDefaultInstance()) return this;
      if (!other.getEquipName().isEmpty()) {
        equipName_ = other.equipName_;
        onChanged();
      }
      if (!other.getEquipId().isEmpty()) {
        equipId_ = other.equipId_;
        onChanged();
      }
      if (!other.getScuLastTxnSync().isEmpty()) {
        scuLastTxnSync_ = other.scuLastTxnSync_;
        onChanged();
      }
      if (!other.getCcuLastTxnSync().isEmpty()) {
        ccuLastTxnSync_ = other.ccuLastTxnSync_;
        onChanged();
      }
      if (!other.getTomIp().isEmpty()) {
        tomIp_ = other.tomIp_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.tom.TOMDeviceInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.tom.TOMDeviceInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object equipName_ = "";
    /**
     * <code>string equip_name = 1;</code>
     * @return The equipName.
     */
    public java.lang.String getEquipName() {
      java.lang.Object ref = equipName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string equip_name = 1;</code>
     * @return The bytes for equipName.
     */
    public com.google.protobuf.ByteString
        getEquipNameBytes() {
      java.lang.Object ref = equipName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string equip_name = 1;</code>
     * @param value The equipName to set.
     * @return This builder for chaining.
     */
    public Builder setEquipName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      equipName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string equip_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipName() {
      
      equipName_ = getDefaultInstance().getEquipName();
      onChanged();
      return this;
    }
    /**
     * <code>string equip_name = 1;</code>
     * @param value The bytes for equipName to set.
     * @return This builder for chaining.
     */
    public Builder setEquipNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      equipName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object equipId_ = "";
    /**
     * <code>string equip_id = 2;</code>
     * @return The equipId.
     */
    public java.lang.String getEquipId() {
      java.lang.Object ref = equipId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return The bytes for equipId.
     */
    public com.google.protobuf.ByteString
        getEquipIdBytes() {
      java.lang.Object ref = equipId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      equipId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipId() {
      
      equipId_ = getDefaultInstance().getEquipId();
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The bytes for equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      equipId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scuLastTxnSync_ = "";
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string scu_last_txn_sync = 3;</code>
     * @return The scuLastTxnSync.
     */
    public java.lang.String getScuLastTxnSync() {
      java.lang.Object ref = scuLastTxnSync_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scuLastTxnSync_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string scu_last_txn_sync = 3;</code>
     * @return The bytes for scuLastTxnSync.
     */
    public com.google.protobuf.ByteString
        getScuLastTxnSyncBytes() {
      java.lang.Object ref = scuLastTxnSync_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scuLastTxnSync_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string scu_last_txn_sync = 3;</code>
     * @param value The scuLastTxnSync to set.
     * @return This builder for chaining.
     */
    public Builder setScuLastTxnSync(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scuLastTxnSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string scu_last_txn_sync = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearScuLastTxnSync() {
      
      scuLastTxnSync_ = getDefaultInstance().getScuLastTxnSync();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string scu_last_txn_sync = 3;</code>
     * @param value The bytes for scuLastTxnSync to set.
     * @return This builder for chaining.
     */
    public Builder setScuLastTxnSyncBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scuLastTxnSync_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ccuLastTxnSync_ = "";
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string ccu_last_txn_sync = 4;</code>
     * @return The ccuLastTxnSync.
     */
    public java.lang.String getCcuLastTxnSync() {
      java.lang.Object ref = ccuLastTxnSync_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ccuLastTxnSync_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string ccu_last_txn_sync = 4;</code>
     * @return The bytes for ccuLastTxnSync.
     */
    public com.google.protobuf.ByteString
        getCcuLastTxnSyncBytes() {
      java.lang.Object ref = ccuLastTxnSync_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ccuLastTxnSync_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string ccu_last_txn_sync = 4;</code>
     * @param value The ccuLastTxnSync to set.
     * @return This builder for chaining.
     */
    public Builder setCcuLastTxnSync(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ccuLastTxnSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string ccu_last_txn_sync = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCcuLastTxnSync() {
      
      ccuLastTxnSync_ = getDefaultInstance().getCcuLastTxnSync();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *colon seperated last_txn:last_sync
     * </pre>
     *
     * <code>string ccu_last_txn_sync = 4;</code>
     * @param value The bytes for ccuLastTxnSync to set.
     * @return This builder for chaining.
     */
    public Builder setCcuLastTxnSyncBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ccuLastTxnSync_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tomIp_ = "";
    /**
     * <code>string tom_ip = 5;</code>
     * @return The tomIp.
     */
    public java.lang.String getTomIp() {
      java.lang.Object ref = tomIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tomIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tom_ip = 5;</code>
     * @return The bytes for tomIp.
     */
    public com.google.protobuf.ByteString
        getTomIpBytes() {
      java.lang.Object ref = tomIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tomIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tom_ip = 5;</code>
     * @param value The tomIp to set.
     * @return This builder for chaining.
     */
    public Builder setTomIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tomIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tom_ip = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTomIp() {
      
      tomIp_ = getDefaultInstance().getTomIp();
      onChanged();
      return this;
    }
    /**
     * <code>string tom_ip = 5;</code>
     * @param value The bytes for tomIp to set.
     * @return This builder for chaining.
     */
    public Builder setTomIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tomIp_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.TOMDeviceInfo)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.TOMDeviceInfo)
  private static final org.network.monitorandcontrol.tom.TOMDeviceInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.tom.TOMDeviceInfo();
  }

  public static org.network.monitorandcontrol.tom.TOMDeviceInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TOMDeviceInfo>
      PARSER = new com.google.protobuf.AbstractParser<TOMDeviceInfo>() {
    @java.lang.Override
    public TOMDeviceInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TOMDeviceInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TOMDeviceInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TOMDeviceInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.tom.TOMDeviceInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

