// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public interface TOMModeControlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.TOMModeControl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.monitoring.proto.OperationMode operation_mode = 1;</code>
   * @return The enum numeric value on the wire for operationMode.
   */
  int getOperationModeValue();
  /**
   * <code>.org.monitoring.proto.OperationMode operation_mode = 1;</code>
   * @return The operationMode.
   */
  org.network.monitorandcontrol.OperationMode getOperationMode();

  /**
   * <code>bool card_process_mode = 2;</code>
   * @return The cardProcessMode.
   */
  boolean getCardProcessMode();

  /**
   * <code>bool qr_sale_mode = 3;</code>
   * @return The qrSaleMode.
   */
  boolean getQrSaleMode();

  /**
   * <code>.org.monitoring.proto.SpecialMode special_mode = 4;</code>
   * @return The enum numeric value on the wire for specialMode.
   */
  int getSpecialModeValue();
  /**
   * <code>.org.monitoring.proto.SpecialMode special_mode = 4;</code>
   * @return The specialMode.
   */
  org.network.monitorandcontrol.SpecialMode getSpecialMode();
}
