// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public interface TOMPeripheralStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.TOMPeripheralStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool scu_connected = 1;</code>
   * @return The scuConnected.
   */
  boolean getScuConnected();

  /**
   * <code>bool ccu_connected = 2;</code>
   * @return The ccuConnected.
   */
  boolean getCcuConnected();

  /**
   * <code>bool reader_connected = 3;</code>
   * @return The readerConnected.
   */
  boolean getReaderConnected();

  /**
   * <code>bool scanner_connected = 4;</code>
   * @return The scannerConnected.
   */
  boolean getScannerConnected();

  /**
   * <code>bool ticket_printer_connected = 5;</code>
   * @return The ticketPrinterConnected.
   */
  boolean getTicketPrinterConnected();

  /**
   * <code>bool receipt_printer_connected = 6;</code>
   * @return The receiptPrinterConnected.
   */
  boolean getReceiptPrinterConnected();

  /**
   * <code>bool pdu_connected = 7;</code>
   * @return The pduConnected.
   */
  boolean getPduConnected();

  /**
   * <code>bool cash_drawer_connected = 8;</code>
   * @return The cashDrawerConnected.
   */
  boolean getCashDrawerConnected();

  /**
   * <code>repeated string alarms = 9;</code>
   * @return A list containing the alarms.
   */
  java.util.List<java.lang.String>
      getAlarmsList();
  /**
   * <code>repeated string alarms = 9;</code>
   * @return The count of alarms.
   */
  int getAlarmsCount();
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the element to return.
   * @return The alarms at the given index.
   */
  java.lang.String getAlarms(int index);
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the alarms at the given index.
   */
  com.google.protobuf.ByteString
      getAlarmsBytes(int index);
}
