// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

/**
 * Protobuf type {@code org.monitoring.proto.TOMPeripheralStatus}
 */
public  final class TOMPeripheralStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.TOMPeripheralStatus)
    TOMPeripheralStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TOMPeripheralStatus.newBuilder() to construct.
  private TOMPeripheralStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TOMPeripheralStatus() {
    alarms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TOMPeripheralStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TOMPeripheralStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            scuConnected_ = input.readBool();
            break;
          }
          case 16: {

            ccuConnected_ = input.readBool();
            break;
          }
          case 24: {

            readerConnected_ = input.readBool();
            break;
          }
          case 32: {

            scannerConnected_ = input.readBool();
            break;
          }
          case 40: {

            ticketPrinterConnected_ = input.readBool();
            break;
          }
          case 48: {

            receiptPrinterConnected_ = input.readBool();
            break;
          }
          case 56: {

            pduConnected_ = input.readBool();
            break;
          }
          case 64: {

            cashDrawerConnected_ = input.readBool();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              alarms_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            alarms_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        alarms_ = alarms_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMPeripheralStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.tom.TOMPeripheralStatus.class, org.network.monitorandcontrol.tom.TOMPeripheralStatus.Builder.class);
  }

  public static final int SCU_CONNECTED_FIELD_NUMBER = 1;
  private boolean scuConnected_;
  /**
   * <code>bool scu_connected = 1;</code>
   * @return The scuConnected.
   */
  public boolean getScuConnected() {
    return scuConnected_;
  }

  public static final int CCU_CONNECTED_FIELD_NUMBER = 2;
  private boolean ccuConnected_;
  /**
   * <code>bool ccu_connected = 2;</code>
   * @return The ccuConnected.
   */
  public boolean getCcuConnected() {
    return ccuConnected_;
  }

  public static final int READER_CONNECTED_FIELD_NUMBER = 3;
  private boolean readerConnected_;
  /**
   * <code>bool reader_connected = 3;</code>
   * @return The readerConnected.
   */
  public boolean getReaderConnected() {
    return readerConnected_;
  }

  public static final int SCANNER_CONNECTED_FIELD_NUMBER = 4;
  private boolean scannerConnected_;
  /**
   * <code>bool scanner_connected = 4;</code>
   * @return The scannerConnected.
   */
  public boolean getScannerConnected() {
    return scannerConnected_;
  }

  public static final int TICKET_PRINTER_CONNECTED_FIELD_NUMBER = 5;
  private boolean ticketPrinterConnected_;
  /**
   * <code>bool ticket_printer_connected = 5;</code>
   * @return The ticketPrinterConnected.
   */
  public boolean getTicketPrinterConnected() {
    return ticketPrinterConnected_;
  }

  public static final int RECEIPT_PRINTER_CONNECTED_FIELD_NUMBER = 6;
  private boolean receiptPrinterConnected_;
  /**
   * <code>bool receipt_printer_connected = 6;</code>
   * @return The receiptPrinterConnected.
   */
  public boolean getReceiptPrinterConnected() {
    return receiptPrinterConnected_;
  }

  public static final int PDU_CONNECTED_FIELD_NUMBER = 7;
  private boolean pduConnected_;
  /**
   * <code>bool pdu_connected = 7;</code>
   * @return The pduConnected.
   */
  public boolean getPduConnected() {
    return pduConnected_;
  }

  public static final int CASH_DRAWER_CONNECTED_FIELD_NUMBER = 8;
  private boolean cashDrawerConnected_;
  /**
   * <code>bool cash_drawer_connected = 8;</code>
   * @return The cashDrawerConnected.
   */
  public boolean getCashDrawerConnected() {
    return cashDrawerConnected_;
  }

  public static final int ALARMS_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList alarms_;
  /**
   * <code>repeated string alarms = 9;</code>
   * @return A list containing the alarms.
   */
  public com.google.protobuf.ProtocolStringList
      getAlarmsList() {
    return alarms_;
  }
  /**
   * <code>repeated string alarms = 9;</code>
   * @return The count of alarms.
   */
  public int getAlarmsCount() {
    return alarms_.size();
  }
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the element to return.
   * @return The alarms at the given index.
   */
  public java.lang.String getAlarms(int index) {
    return alarms_.get(index);
  }
  /**
   * <code>repeated string alarms = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the alarms at the given index.
   */
  public com.google.protobuf.ByteString
      getAlarmsBytes(int index) {
    return alarms_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scuConnected_ != false) {
      output.writeBool(1, scuConnected_);
    }
    if (ccuConnected_ != false) {
      output.writeBool(2, ccuConnected_);
    }
    if (readerConnected_ != false) {
      output.writeBool(3, readerConnected_);
    }
    if (scannerConnected_ != false) {
      output.writeBool(4, scannerConnected_);
    }
    if (ticketPrinterConnected_ != false) {
      output.writeBool(5, ticketPrinterConnected_);
    }
    if (receiptPrinterConnected_ != false) {
      output.writeBool(6, receiptPrinterConnected_);
    }
    if (pduConnected_ != false) {
      output.writeBool(7, pduConnected_);
    }
    if (cashDrawerConnected_ != false) {
      output.writeBool(8, cashDrawerConnected_);
    }
    for (int i = 0; i < alarms_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, alarms_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scuConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, scuConnected_);
    }
    if (ccuConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ccuConnected_);
    }
    if (readerConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, readerConnected_);
    }
    if (scannerConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, scannerConnected_);
    }
    if (ticketPrinterConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, ticketPrinterConnected_);
    }
    if (receiptPrinterConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, receiptPrinterConnected_);
    }
    if (pduConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, pduConnected_);
    }
    if (cashDrawerConnected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, cashDrawerConnected_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < alarms_.size(); i++) {
        dataSize += computeStringSizeNoTag(alarms_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAlarmsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.tom.TOMPeripheralStatus)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.tom.TOMPeripheralStatus other = (org.network.monitorandcontrol.tom.TOMPeripheralStatus) obj;

    if (getScuConnected()
        != other.getScuConnected()) return false;
    if (getCcuConnected()
        != other.getCcuConnected()) return false;
    if (getReaderConnected()
        != other.getReaderConnected()) return false;
    if (getScannerConnected()
        != other.getScannerConnected()) return false;
    if (getTicketPrinterConnected()
        != other.getTicketPrinterConnected()) return false;
    if (getReceiptPrinterConnected()
        != other.getReceiptPrinterConnected()) return false;
    if (getPduConnected()
        != other.getPduConnected()) return false;
    if (getCashDrawerConnected()
        != other.getCashDrawerConnected()) return false;
    if (!getAlarmsList()
        .equals(other.getAlarmsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getScuConnected());
    hash = (37 * hash) + CCU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCcuConnected());
    hash = (37 * hash) + READER_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReaderConnected());
    hash = (37 * hash) + SCANNER_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getScannerConnected());
    hash = (37 * hash) + TICKET_PRINTER_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTicketPrinterConnected());
    hash = (37 * hash) + RECEIPT_PRINTER_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReceiptPrinterConnected());
    hash = (37 * hash) + PDU_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPduConnected());
    hash = (37 * hash) + CASH_DRAWER_CONNECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCashDrawerConnected());
    if (getAlarmsCount() > 0) {
      hash = (37 * hash) + ALARMS_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.tom.TOMPeripheralStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.monitoring.proto.TOMPeripheralStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.TOMPeripheralStatus)
      org.network.monitorandcontrol.tom.TOMPeripheralStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMPeripheralStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.tom.TOMPeripheralStatus.class, org.network.monitorandcontrol.tom.TOMPeripheralStatus.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.tom.TOMPeripheralStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      scuConnected_ = false;

      ccuConnected_ = false;

      readerConnected_ = false;

      scannerConnected_ = false;

      ticketPrinterConnected_ = false;

      receiptPrinterConnected_ = false;

      pduConnected_ = false;

      cashDrawerConnected_ = false;

      alarms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.tom.TOM.internal_static_org_monitoring_proto_TOMPeripheralStatus_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMPeripheralStatus getDefaultInstanceForType() {
      return org.network.monitorandcontrol.tom.TOMPeripheralStatus.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMPeripheralStatus build() {
      org.network.monitorandcontrol.tom.TOMPeripheralStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.tom.TOMPeripheralStatus buildPartial() {
      org.network.monitorandcontrol.tom.TOMPeripheralStatus result = new org.network.monitorandcontrol.tom.TOMPeripheralStatus(this);
      int from_bitField0_ = bitField0_;
      result.scuConnected_ = scuConnected_;
      result.ccuConnected_ = ccuConnected_;
      result.readerConnected_ = readerConnected_;
      result.scannerConnected_ = scannerConnected_;
      result.ticketPrinterConnected_ = ticketPrinterConnected_;
      result.receiptPrinterConnected_ = receiptPrinterConnected_;
      result.pduConnected_ = pduConnected_;
      result.cashDrawerConnected_ = cashDrawerConnected_;
      if (((bitField0_ & 0x00000001) != 0)) {
        alarms_ = alarms_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.alarms_ = alarms_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.tom.TOMPeripheralStatus) {
        return mergeFrom((org.network.monitorandcontrol.tom.TOMPeripheralStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.tom.TOMPeripheralStatus other) {
      if (other == org.network.monitorandcontrol.tom.TOMPeripheralStatus.getDefaultInstance()) return this;
      if (other.getScuConnected() != false) {
        setScuConnected(other.getScuConnected());
      }
      if (other.getCcuConnected() != false) {
        setCcuConnected(other.getCcuConnected());
      }
      if (other.getReaderConnected() != false) {
        setReaderConnected(other.getReaderConnected());
      }
      if (other.getScannerConnected() != false) {
        setScannerConnected(other.getScannerConnected());
      }
      if (other.getTicketPrinterConnected() != false) {
        setTicketPrinterConnected(other.getTicketPrinterConnected());
      }
      if (other.getReceiptPrinterConnected() != false) {
        setReceiptPrinterConnected(other.getReceiptPrinterConnected());
      }
      if (other.getPduConnected() != false) {
        setPduConnected(other.getPduConnected());
      }
      if (other.getCashDrawerConnected() != false) {
        setCashDrawerConnected(other.getCashDrawerConnected());
      }
      if (!other.alarms_.isEmpty()) {
        if (alarms_.isEmpty()) {
          alarms_ = other.alarms_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAlarmsIsMutable();
          alarms_.addAll(other.alarms_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.tom.TOMPeripheralStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.tom.TOMPeripheralStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean scuConnected_ ;
    /**
     * <code>bool scu_connected = 1;</code>
     * @return The scuConnected.
     */
    public boolean getScuConnected() {
      return scuConnected_;
    }
    /**
     * <code>bool scu_connected = 1;</code>
     * @param value The scuConnected to set.
     * @return This builder for chaining.
     */
    public Builder setScuConnected(boolean value) {
      
      scuConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool scu_connected = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScuConnected() {
      
      scuConnected_ = false;
      onChanged();
      return this;
    }

    private boolean ccuConnected_ ;
    /**
     * <code>bool ccu_connected = 2;</code>
     * @return The ccuConnected.
     */
    public boolean getCcuConnected() {
      return ccuConnected_;
    }
    /**
     * <code>bool ccu_connected = 2;</code>
     * @param value The ccuConnected to set.
     * @return This builder for chaining.
     */
    public Builder setCcuConnected(boolean value) {
      
      ccuConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ccu_connected = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCcuConnected() {
      
      ccuConnected_ = false;
      onChanged();
      return this;
    }

    private boolean readerConnected_ ;
    /**
     * <code>bool reader_connected = 3;</code>
     * @return The readerConnected.
     */
    public boolean getReaderConnected() {
      return readerConnected_;
    }
    /**
     * <code>bool reader_connected = 3;</code>
     * @param value The readerConnected to set.
     * @return This builder for chaining.
     */
    public Builder setReaderConnected(boolean value) {
      
      readerConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool reader_connected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReaderConnected() {
      
      readerConnected_ = false;
      onChanged();
      return this;
    }

    private boolean scannerConnected_ ;
    /**
     * <code>bool scanner_connected = 4;</code>
     * @return The scannerConnected.
     */
    public boolean getScannerConnected() {
      return scannerConnected_;
    }
    /**
     * <code>bool scanner_connected = 4;</code>
     * @param value The scannerConnected to set.
     * @return This builder for chaining.
     */
    public Builder setScannerConnected(boolean value) {
      
      scannerConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool scanner_connected = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScannerConnected() {
      
      scannerConnected_ = false;
      onChanged();
      return this;
    }

    private boolean ticketPrinterConnected_ ;
    /**
     * <code>bool ticket_printer_connected = 5;</code>
     * @return The ticketPrinterConnected.
     */
    public boolean getTicketPrinterConnected() {
      return ticketPrinterConnected_;
    }
    /**
     * <code>bool ticket_printer_connected = 5;</code>
     * @param value The ticketPrinterConnected to set.
     * @return This builder for chaining.
     */
    public Builder setTicketPrinterConnected(boolean value) {
      
      ticketPrinterConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ticket_printer_connected = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicketPrinterConnected() {
      
      ticketPrinterConnected_ = false;
      onChanged();
      return this;
    }

    private boolean receiptPrinterConnected_ ;
    /**
     * <code>bool receipt_printer_connected = 6;</code>
     * @return The receiptPrinterConnected.
     */
    public boolean getReceiptPrinterConnected() {
      return receiptPrinterConnected_;
    }
    /**
     * <code>bool receipt_printer_connected = 6;</code>
     * @param value The receiptPrinterConnected to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptPrinterConnected(boolean value) {
      
      receiptPrinterConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool receipt_printer_connected = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiptPrinterConnected() {
      
      receiptPrinterConnected_ = false;
      onChanged();
      return this;
    }

    private boolean pduConnected_ ;
    /**
     * <code>bool pdu_connected = 7;</code>
     * @return The pduConnected.
     */
    public boolean getPduConnected() {
      return pduConnected_;
    }
    /**
     * <code>bool pdu_connected = 7;</code>
     * @param value The pduConnected to set.
     * @return This builder for chaining.
     */
    public Builder setPduConnected(boolean value) {
      
      pduConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool pdu_connected = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPduConnected() {
      
      pduConnected_ = false;
      onChanged();
      return this;
    }

    private boolean cashDrawerConnected_ ;
    /**
     * <code>bool cash_drawer_connected = 8;</code>
     * @return The cashDrawerConnected.
     */
    public boolean getCashDrawerConnected() {
      return cashDrawerConnected_;
    }
    /**
     * <code>bool cash_drawer_connected = 8;</code>
     * @param value The cashDrawerConnected to set.
     * @return This builder for chaining.
     */
    public Builder setCashDrawerConnected(boolean value) {
      
      cashDrawerConnected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool cash_drawer_connected = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCashDrawerConnected() {
      
      cashDrawerConnected_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList alarms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAlarmsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alarms_ = new com.google.protobuf.LazyStringArrayList(alarms_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @return A list containing the alarms.
     */
    public com.google.protobuf.ProtocolStringList
        getAlarmsList() {
      return alarms_.getUnmodifiableView();
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @return The count of alarms.
     */
    public int getAlarmsCount() {
      return alarms_.size();
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param index The index of the element to return.
     * @return The alarms at the given index.
     */
    public java.lang.String getAlarms(int index) {
      return alarms_.get(index);
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the alarms at the given index.
     */
    public com.google.protobuf.ByteString
        getAlarmsBytes(int index) {
      return alarms_.getByteString(index);
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param index The index to set the value at.
     * @param value The alarms to set.
     * @return This builder for chaining.
     */
    public Builder setAlarms(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAlarmsIsMutable();
      alarms_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param value The alarms to add.
     * @return This builder for chaining.
     */
    public Builder addAlarms(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAlarmsIsMutable();
      alarms_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param values The alarms to add.
     * @return This builder for chaining.
     */
    public Builder addAllAlarms(
        java.lang.Iterable<java.lang.String> values) {
      ensureAlarmsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, alarms_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlarms() {
      alarms_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string alarms = 9;</code>
     * @param value The bytes of the alarms to add.
     * @return This builder for chaining.
     */
    public Builder addAlarmsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAlarmsIsMutable();
      alarms_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.TOMPeripheralStatus)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.TOMPeripheralStatus)
  private static final org.network.monitorandcontrol.tom.TOMPeripheralStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.tom.TOMPeripheralStatus();
  }

  public static org.network.monitorandcontrol.tom.TOMPeripheralStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TOMPeripheralStatus>
      PARSER = new com.google.protobuf.AbstractParser<TOMPeripheralStatus>() {
    @java.lang.Override
    public TOMPeripheralStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TOMPeripheralStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TOMPeripheralStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TOMPeripheralStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.tom.TOMPeripheralStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

