// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public interface TOMPeripheralStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.TOMPeripheralStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool scu_connected = 1;</code>
   * @return The scuConnected.
   */
  boolean getScuConnected();

  /**
   * <code>bool ccu_connected = 2;</code>
   * @return The ccuConnected.
   */
  boolean getCcuConnected();

  /**
   * <code>bool reader_connected = 3;</code>
   * @return The readerConnected.
   */
  boolean getReaderConnected();

  /**
   * <code>bool scanner_connected = 4;</code>
   * @return The scannerConnected.
   */
  boolean getScannerConnected();

  /**
   * <code>bool printer_connected = 5;</code>
   * @return The printerConnected.
   */
  boolean getPrinterConnected();

  /**
   * <code>bool pdu_connected = 6;</code>
   * @return The pduConnected.
   */
  boolean getPduConnected();

  /**
   * <code>bool cash_drawer_connected = 7;</code>
   * @return The cashDrawerConnected.
   */
  boolean getCashDrawerConnected();

  /**
   * <code>bool ups_connected = 8;</code>
   * @return The upsConnected.
   */
  boolean getUpsConnected();
}
