// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TOM.proto

package org.network.monitorandcontrol.tom;

public interface TOMResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.TOMResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>string error_msg = 2;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <code>string error_msg = 2;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();

  /**
   * <code>.google.protobuf.Any request_data = 3;</code>
   * @return Whether the requestData field is set.
   */
  boolean hasRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 3;</code>
   * @return The requestData.
   */
  com.google.protobuf.Any getRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getRequestDataOrBuilder();
}
