// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.proto

package org.network.monitorandcontrol.scu_console;

public interface ConsoleStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.ConsoleStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string console_id = 2;</code>
   * @return The consoleId.
   */
  java.lang.String getConsoleId();
  /**
   * <code>string console_id = 2;</code>
   * @return The bytes for consoleId.
   */
  com.google.protobuf.ByteString
      getConsoleIdBytes();

  /**
   * <code>int32 status_code = 3;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>string error_msg = 4;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <code>string error_msg = 4;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();
}
