// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.proto

package org.network.monitorandcontrol.scu_console;

public final class SC {
  private SC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_PushUpdates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_PushUpdates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_ConsoleStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_ConsoleStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010SC.proto\022\024org.monitoring.proto\"V\n\013Push" +
      "Updates\022\n\n\002ip\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\023" +
      "\n\013device_name\030\003 \001(\t\022\023\n\013isconnected\030\004 \001(\010" +
      "\"W\n\rConsoleStream\022\n\n\002ip\030\001 \001(\t\022\022\n\nconsole" +
      "_id\030\002 \001(\t\022\023\n\013status_code\030\003 \001(\005\022\021\n\terror_" +
      "msg\030\004 \001(\tB-\n)org.network.monitorandcontr" +
      "ol.scu_consoleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_monitoring_proto_PushUpdates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_monitoring_proto_PushUpdates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_PushUpdates_descriptor,
        new java.lang.String[] { "Ip", "DeviceId", "DeviceName", "Isconnected", });
    internal_static_org_monitoring_proto_ConsoleStream_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_monitoring_proto_ConsoleStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_ConsoleStream_descriptor,
        new java.lang.String[] { "Ip", "ConsoleId", "StatusCode", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
