// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.proto

package org.network.monitorandcontrol.scu_console;

public final class SC {
  private SC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_ConsoleProtocol_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_ConsoleProtocol_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_monitoring_proto_StreamData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_monitoring_proto_StreamData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010SC.proto\022\024org.monitoring.proto\032\013Enums." +
      "proto\032\031google/protobuf/any.proto\"\273\001\n\017Con" +
      "soleProtocol\022\022\n\nconsole_id\030\001 \001(\t\022\023\n\013stat" +
      "us_code\030\002 \001(\005\022\021\n\terror_msg\030\003 \001(\t\0225\n\013stre" +
      "am_data\030\004 \001(\0132 .org.monitoring.proto.Str" +
      "eamData\0225\n\013device_type\030\005 \001(\0162 .org.monit" +
      "oring.proto.DeviceType\"\274\001\n\nStreamData\0227\n" +
      "\014command_type\030\001 \001(\0162!.org.monitoring.pro" +
      "to.CommandType\022\020\n\010equip_id\030\002 \001(\t\0227\n\014requ" +
      "est_type\030\003 \001(\0162!.org.monitoring.proto.Re" +
      "questType\022*\n\014request_data\030\004 \001(\0132\024.google" +
      ".protobuf.AnyB-\n)org.network.monitorandc" +
      "ontrol.scu_consoleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.network.monitorandcontrol.Enums.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_org_monitoring_proto_ConsoleProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_monitoring_proto_ConsoleProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_ConsoleProtocol_descriptor,
        new java.lang.String[] { "ConsoleId", "StatusCode", "ErrorMsg", "StreamData", "DeviceType", });
    internal_static_org_monitoring_proto_StreamData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_monitoring_proto_StreamData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_monitoring_proto_StreamData_descriptor,
        new java.lang.String[] { "CommandType", "EquipId", "RequestType", "RequestData", });
    org.network.monitorandcontrol.Enums.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
