// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.proto

package org.network.monitorandcontrol.scu_console;

/**
 * Protobuf type {@code org.monitoring.proto.StreamData}
 */
public  final class StreamData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.monitoring.proto.StreamData)
    StreamDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamData.newBuilder() to construct.
  private StreamData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamData() {
    commandType_ = 0;
    equipId_ = "";
    requestType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            commandType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            equipId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            requestType_ = rawValue;
            break;
          }
          case 34: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (requestData_ != null) {
              subBuilder = requestData_.toBuilder();
            }
            requestData_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestData_);
              requestData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.network.monitorandcontrol.scu_console.SC.internal_static_org_monitoring_proto_StreamData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.network.monitorandcontrol.scu_console.SC.internal_static_org_monitoring_proto_StreamData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.network.monitorandcontrol.scu_console.StreamData.class, org.network.monitorandcontrol.scu_console.StreamData.Builder.class);
  }

  public static final int COMMAND_TYPE_FIELD_NUMBER = 1;
  private int commandType_;
  /**
   * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
   * @return The enum numeric value on the wire for commandType.
   */
  public int getCommandTypeValue() {
    return commandType_;
  }
  /**
   * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
   * @return The commandType.
   */
  public org.network.monitorandcontrol.CommandType getCommandType() {
    @SuppressWarnings("deprecation")
    org.network.monitorandcontrol.CommandType result = org.network.monitorandcontrol.CommandType.valueOf(commandType_);
    return result == null ? org.network.monitorandcontrol.CommandType.UNRECOGNIZED : result;
  }

  public static final int EQUIP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object equipId_;
  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  public java.lang.String getEquipId() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      equipId_ = s;
      return s;
    }
  }
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  public com.google.protobuf.ByteString
      getEquipIdBytes() {
    java.lang.Object ref = equipId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      equipId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_TYPE_FIELD_NUMBER = 3;
  private int requestType_;
  /**
   * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  public int getRequestTypeValue() {
    return requestType_;
  }
  /**
   * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
   * @return The requestType.
   */
  public org.network.monitorandcontrol.RequestType getRequestType() {
    @SuppressWarnings("deprecation")
    org.network.monitorandcontrol.RequestType result = org.network.monitorandcontrol.RequestType.valueOf(requestType_);
    return result == null ? org.network.monitorandcontrol.RequestType.UNRECOGNIZED : result;
  }

  public static final int REQUEST_DATA_FIELD_NUMBER = 4;
  private com.google.protobuf.Any requestData_;
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return Whether the requestData field is set.
   */
  public boolean hasRequestData() {
    return requestData_ != null;
  }
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return The requestData.
   */
  public com.google.protobuf.Any getRequestData() {
    return requestData_ == null ? com.google.protobuf.Any.getDefaultInstance() : requestData_;
  }
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   */
  public com.google.protobuf.AnyOrBuilder getRequestDataOrBuilder() {
    return getRequestData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (commandType_ != org.network.monitorandcontrol.CommandType.UNKNOWN_COMMAND.getNumber()) {
      output.writeEnum(1, commandType_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, equipId_);
    }
    if (requestType_ != org.network.monitorandcontrol.RequestType.DIVICE_DISCONNECT.getNumber()) {
      output.writeEnum(3, requestType_);
    }
    if (requestData_ != null) {
      output.writeMessage(4, getRequestData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (commandType_ != org.network.monitorandcontrol.CommandType.UNKNOWN_COMMAND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, commandType_);
    }
    if (!getEquipIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, equipId_);
    }
    if (requestType_ != org.network.monitorandcontrol.RequestType.DIVICE_DISCONNECT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, requestType_);
    }
    if (requestData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRequestData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.network.monitorandcontrol.scu_console.StreamData)) {
      return super.equals(obj);
    }
    org.network.monitorandcontrol.scu_console.StreamData other = (org.network.monitorandcontrol.scu_console.StreamData) obj;

    if (commandType_ != other.commandType_) return false;
    if (!getEquipId()
        .equals(other.getEquipId())) return false;
    if (requestType_ != other.requestType_) return false;
    if (hasRequestData() != other.hasRequestData()) return false;
    if (hasRequestData()) {
      if (!getRequestData()
          .equals(other.getRequestData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + commandType_;
    hash = (37 * hash) + EQUIP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEquipId().hashCode();
    hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + requestType_;
    if (hasRequestData()) {
      hash = (37 * hash) + REQUEST_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.network.monitorandcontrol.scu_console.StreamData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.network.monitorandcontrol.scu_console.StreamData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.monitoring.proto.StreamData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.monitoring.proto.StreamData)
      org.network.monitorandcontrol.scu_console.StreamDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.network.monitorandcontrol.scu_console.SC.internal_static_org_monitoring_proto_StreamData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.network.monitorandcontrol.scu_console.SC.internal_static_org_monitoring_proto_StreamData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.network.monitorandcontrol.scu_console.StreamData.class, org.network.monitorandcontrol.scu_console.StreamData.Builder.class);
    }

    // Construct using org.network.monitorandcontrol.scu_console.StreamData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      commandType_ = 0;

      equipId_ = "";

      requestType_ = 0;

      if (requestDataBuilder_ == null) {
        requestData_ = null;
      } else {
        requestData_ = null;
        requestDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.network.monitorandcontrol.scu_console.SC.internal_static_org_monitoring_proto_StreamData_descriptor;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.scu_console.StreamData getDefaultInstanceForType() {
      return org.network.monitorandcontrol.scu_console.StreamData.getDefaultInstance();
    }

    @java.lang.Override
    public org.network.monitorandcontrol.scu_console.StreamData build() {
      org.network.monitorandcontrol.scu_console.StreamData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.network.monitorandcontrol.scu_console.StreamData buildPartial() {
      org.network.monitorandcontrol.scu_console.StreamData result = new org.network.monitorandcontrol.scu_console.StreamData(this);
      result.commandType_ = commandType_;
      result.equipId_ = equipId_;
      result.requestType_ = requestType_;
      if (requestDataBuilder_ == null) {
        result.requestData_ = requestData_;
      } else {
        result.requestData_ = requestDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.network.monitorandcontrol.scu_console.StreamData) {
        return mergeFrom((org.network.monitorandcontrol.scu_console.StreamData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.network.monitorandcontrol.scu_console.StreamData other) {
      if (other == org.network.monitorandcontrol.scu_console.StreamData.getDefaultInstance()) return this;
      if (other.commandType_ != 0) {
        setCommandTypeValue(other.getCommandTypeValue());
      }
      if (!other.getEquipId().isEmpty()) {
        equipId_ = other.equipId_;
        onChanged();
      }
      if (other.requestType_ != 0) {
        setRequestTypeValue(other.getRequestTypeValue());
      }
      if (other.hasRequestData()) {
        mergeRequestData(other.getRequestData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.network.monitorandcontrol.scu_console.StreamData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.network.monitorandcontrol.scu_console.StreamData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int commandType_ = 0;
    /**
     * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
     * @return The enum numeric value on the wire for commandType.
     */
    public int getCommandTypeValue() {
      return commandType_;
    }
    /**
     * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
     * @param value The enum numeric value on the wire for commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandTypeValue(int value) {
      commandType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
     * @return The commandType.
     */
    public org.network.monitorandcontrol.CommandType getCommandType() {
      @SuppressWarnings("deprecation")
      org.network.monitorandcontrol.CommandType result = org.network.monitorandcontrol.CommandType.valueOf(commandType_);
      return result == null ? org.network.monitorandcontrol.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
     * @param value The commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandType(org.network.monitorandcontrol.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      commandType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandType() {
      
      commandType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object equipId_ = "";
    /**
     * <code>string equip_id = 2;</code>
     * @return The equipId.
     */
    public java.lang.String getEquipId() {
      java.lang.Object ref = equipId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return The bytes for equipId.
     */
    public com.google.protobuf.ByteString
        getEquipIdBytes() {
      java.lang.Object ref = equipId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      equipId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipId() {
      
      equipId_ = getDefaultInstance().getEquipId();
      onChanged();
      return this;
    }
    /**
     * <code>string equip_id = 2;</code>
     * @param value The bytes for equipId to set.
     * @return This builder for chaining.
     */
    public Builder setEquipIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      equipId_ = value;
      onChanged();
      return this;
    }

    private int requestType_ = 0;
    /**
     * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
     * @param value The enum numeric value on the wire for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeValue(int value) {
      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
     * @return The requestType.
     */
    public org.network.monitorandcontrol.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      org.network.monitorandcontrol.RequestType result = org.network.monitorandcontrol.RequestType.valueOf(requestType_);
      return result == null ? org.network.monitorandcontrol.RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(org.network.monitorandcontrol.RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      requestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {
      
      requestType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any requestData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> requestDataBuilder_;
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     * @return Whether the requestData field is set.
     */
    public boolean hasRequestData() {
      return requestDataBuilder_ != null || requestData_ != null;
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     * @return The requestData.
     */
    public com.google.protobuf.Any getRequestData() {
      if (requestDataBuilder_ == null) {
        return requestData_ == null ? com.google.protobuf.Any.getDefaultInstance() : requestData_;
      } else {
        return requestDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public Builder setRequestData(com.google.protobuf.Any value) {
      if (requestDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestData_ = value;
        onChanged();
      } else {
        requestDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public Builder setRequestData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (requestDataBuilder_ == null) {
        requestData_ = builderForValue.build();
        onChanged();
      } else {
        requestDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public Builder mergeRequestData(com.google.protobuf.Any value) {
      if (requestDataBuilder_ == null) {
        if (requestData_ != null) {
          requestData_ =
            com.google.protobuf.Any.newBuilder(requestData_).mergeFrom(value).buildPartial();
        } else {
          requestData_ = value;
        }
        onChanged();
      } else {
        requestDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public Builder clearRequestData() {
      if (requestDataBuilder_ == null) {
        requestData_ = null;
        onChanged();
      } else {
        requestData_ = null;
        requestDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public com.google.protobuf.Any.Builder getRequestDataBuilder() {
      
      onChanged();
      return getRequestDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getRequestDataOrBuilder() {
      if (requestDataBuilder_ != null) {
        return requestDataBuilder_.getMessageOrBuilder();
      } else {
        return requestData_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : requestData_;
      }
    }
    /**
     * <code>.google.protobuf.Any request_data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getRequestDataFieldBuilder() {
      if (requestDataBuilder_ == null) {
        requestDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getRequestData(),
                getParentForChildren(),
                isClean());
        requestData_ = null;
      }
      return requestDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.monitoring.proto.StreamData)
  }

  // @@protoc_insertion_point(class_scope:org.monitoring.proto.StreamData)
  private static final org.network.monitorandcontrol.scu_console.StreamData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.network.monitorandcontrol.scu_console.StreamData();
  }

  public static org.network.monitorandcontrol.scu_console.StreamData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamData>
      PARSER = new com.google.protobuf.AbstractParser<StreamData>() {
    @java.lang.Override
    public StreamData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.network.monitorandcontrol.scu_console.StreamData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

