// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SC.proto

package org.network.monitorandcontrol.scu_console;

public interface StreamDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.monitoring.proto.StreamData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
   * @return The enum numeric value on the wire for commandType.
   */
  int getCommandTypeValue();
  /**
   * <code>.org.monitoring.proto.CommandType command_type = 1;</code>
   * @return The commandType.
   */
  org.network.monitorandcontrol.CommandType getCommandType();

  /**
   * <code>string equip_id = 2;</code>
   * @return The equipId.
   */
  java.lang.String getEquipId();
  /**
   * <code>string equip_id = 2;</code>
   * @return The bytes for equipId.
   */
  com.google.protobuf.ByteString
      getEquipIdBytes();

  /**
   * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <code>.org.monitoring.proto.RequestType request_type = 3;</code>
   * @return The requestType.
   */
  org.network.monitorandcontrol.RequestType getRequestType();

  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return Whether the requestData field is set.
   */
  boolean hasRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   * @return The requestData.
   */
  com.google.protobuf.Any getRequestData();
  /**
   * <code>.google.protobuf.Any request_data = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getRequestDataOrBuilder();
}
